import { supabase } from './supabase';
function requireCloud(){if(!supabase)throw new Error('Cloud database is not configured.');}
async function rows(table,builder){requireCloud();const{data,error}=await builder(supabase.from(table));if(error)throw error;return Array.isArray(data)?data:(data?[data]:[])}
async function one(table,input){requireCloud();const{data,error}=await supabase.from(table).insert(input).select().single();if(error)throw error;return data}
async function single(table,builder){requireCloud();const{data,error}=await builder(supabase.from(table)).single();if(error)throw error;return data}
async function update(table,id,input){requireCloud();const{data,error}=await supabase.from(table).update(input).eq('id',id).select().single();if(error)throw error;return data}
export const listCustomers=()=>rows('customers',q=>q.select('*').order('name'));export const createCustomer=input=>one('customers',input);export const updateCustomer=(id,input)=>update('customers',id,input);
export const listSites=customerId=>rows('sites',q=>{let x=q.select('*').order('name');return customerId?x.eq('customer_id',customerId):x});export const createSite=input=>one('sites',input);export const updateSite=(id,input)=>update('sites',id,input);
export const listForklifts=()=>rows('forklifts',q=>q.select('*, customers(name), sites(name)').order('plant_number'));export const getForklift=id=>single('forklifts',q=>q.select('*, customers(name), sites(name)').eq('id',id));export const createForklift=input=>one('forklifts',input);export const updateForklift=(id,input)=>update('forklifts',id,input);
export const listJobs=()=>rows('jobs',q=>q.select('*, customers(name), sites(name), forklifts(plant_number,make,model,serial_number)').order('job_date',{ascending:false}));export const getJob=id=>single('jobs',q=>q.select('*, customers(name), sites(name), forklifts(plant_number,make,model,serial_number)').eq('id',id));const validateJobNumbers=input=>{for(const[label,value]of[['Labour hours',input?.labour_hours],['Travel',input?.travel]])if(value!==undefined&&value!==null&&value!==''&&(!Number.isFinite(Number(value))||Number(value)<0))throw new Error(`${label} must be a valid non-negative number.`)};export const createJob=async input=>{validateJobNumbers(input);return one('jobs',input)};export const updateJob=async(id,input)=>{validateJobNumbers(input);return update('jobs',id,input)};
export const addJobPhoto=async(jobId,file,tag='evidence',caption='')=>{const path=await uploadJobFile(jobId,file);return one('job_photos',{job_id:jobId,storage_path:path,tag,caption})};export const listJobPhotos=jobId=>rows('job_photos',q=>q.select('*').eq('job_id',jobId).order('created_at'));const validateJobPartNumbers=input=>{for(const[label,value]of[['Quantity',input?.quantity],['Unit cost',input?.unit_cost]])if(value!==undefined&&value!==null&&value!==''&&(!Number.isFinite(Number(value))||Number(value)<=0))throw new Error(`${label} must be a valid number greater than zero.`)};export const createJobPart=async input=>{validateJobPartNumbers(input);return one('job_parts',input)};export const updateJobPart=async(id,input)=>{validateJobPartNumbers(input);return update('job_parts',id,input)};export const listJobParts=jobId=>rows('job_parts',q=>q.select('*, parts(*)').eq('job_id',jobId).order('created_at'));
export const createServiceEvent=input=>one('service_events',input);export const listServiceEvents=forkliftId=>rows('service_events',q=>q.select('*').eq('forklift_id',forkliftId).order('event_date',{ascending:false}));
export const createForkliftDocument=input=>one('forklift_documents',input);export const listForkliftDocuments=forkliftId=>rows('forklift_documents',q=>q.select('*').eq('forklift_id',forkliftId).order('created_at',{ascending:false}));
export const listSuppliers=()=>rows('suppliers',q=>q.select('*').order('name'));export const createSupplier=input=>one('suppliers',input);export const updateSupplier=(id,input)=>update('suppliers',id,input);export const listParts=()=>rows('parts',q=>q.select('*').eq('active',true).order('description'));export const createPart=input=>one('parts',input);export const updatePart=(id,input)=>update('parts',id,input);
export const listInvoices=()=>rows('invoices',q=>q.select('*, customers(name)').order('created_at',{ascending:false}));export const listPayments=invoiceId=>rows('payments',q=>q.select('*').eq('invoice_id',invoiceId).order('payment_date',{ascending:false}));export const createPayment=async input=>{const amount=Number(input?.amount);if(!input?.invoice_id||!Number.isFinite(amount)||amount<=0)throw new Error('Payment must have an invoice and a positive amount.');const invoice=await getInvoice(input.invoice_id);const existing=await listPayments(input.invoice_id);const paid=existing.reduce((sum,p)=>sum+(Number(p.amount)||0),0);if(amount>Math.max(0,Number(invoice.total||0)-paid)+0.005)throw new Error('Payment cannot exceed the remaining invoice balance.');return one('payments',{...input,amount});};export const getInvoice=id=>single('invoices',q=>q.select('*, customers(name)').eq('id',id));export const createInvoice=async input=>{validateMoneyFields(input,[['Invoice subtotal',input?.subtotal],['Invoice VAT',input?.vat],['Invoice total',input?.total]]);return one('invoices',input)};const validateLineNumbers=(input,label='Line')=>{for(const[name,value]of [['Quantity',input?.quantity],['Unit price',input?.unit_price],['VAT rate',input?.vat_rate]])if(value!==undefined&&value!==null&&value!==''&&(!Number.isFinite(Number(value))||Number(value)<0||name==='Quantity'&&Number(value)<=0))throw new Error(`${label} ${name} must be a valid ${name==='Quantity'?'number greater than zero':'non-negative number'}.`)};export const createInvoiceLine=async input=>{validateLineNumbers(input,'Invoice line');return one('invoice_lines',input)};export const listInvoiceLines=invoiceId=>rows('invoice_lines',q=>q.select('*').eq('invoice_id',invoiceId).order('created_at'));export const updateInvoice=(id,input)=>update('invoices',id,input);
export const listSupplierOrders=()=>rows('supplier_orders',q=>q.select('*, suppliers(name)').order('order_date',{ascending:false}));export const listSupplierOrderLines=orderId=>rows('supplier_order_lines',q=>q.select('*').eq('supplier_order_id',orderId).order('created_at'));export const createSupplierOrder=input=>one('supplier_orders',input);export const updateSupplierOrder=(id,input)=>update('supplier_orders',id,input);const validateSupplierOrderLine=input=>{for(const[label,value]of [['Quantity',input?.quantity],['Unit cost',input?.unit_cost]])if(value!==undefined&&value!==null&&value!==''&&(!Number.isFinite(Number(value))||Number(value)<0||label==='Quantity'&&Number(value)<=0))throw new Error(`${label} must be a valid ${label==='Quantity'?'number greater than zero':'non-negative number'}.`)};export const createSupplierOrderLine=async input=>{validateSupplierOrderLine(input);return one('supplier_order_lines',input)};export const linkSupplierLineToJob=(id,job_id)=>update('supplier_order_lines',id,{job_id});export const linkSupplierLineToJobPart=(id,jobPartId)=>update('supplier_order_lines',id,{job_part_id:jobPartId});
export const listJobStatusHistory=jobId=>rows('job_status_history',q=>q.select('*').eq('job_id',jobId).order('changed_at',{ascending:false}));const allowedJobTransitions={draft:['in_progress','awaiting_parts','completed'],in_progress:['awaiting_parts','completed'],awaiting_parts:['in_progress','completed'],completed:[],cancelled:[]};export async function addJobStatusHistory(jobId,oldStatus,newStatus,note=''){requireCloud();const{data:{user}={}}=await supabase.auth.getUser();return one('job_status_history',{job_id:jobId,old_status:oldStatus||null,new_status:newStatus,changed_by:user?.id||null,note:note||null})}export async function saveJobStatus(jobId,oldStatus,newStatus,note=''){const from=String(oldStatus||'draft').toLowerCase(),to=String(newStatus||'').toLowerCase();if(!to||to===from)return getJob(jobId);if(!allowedJobTransitions[from]?.includes(to))throw new Error(`Invalid jobsheet status transition: ${from} → ${to}.`);const job=await updateJob(jobId,{status:to});if(oldStatus!==newStatus)await addJobStatusHistory(jobId,oldStatus,newStatus,note);return job}
export async function uploadJobFile(jobId,file){requireCloud();const safe=String(file.name||'upload').replace(/[^a-zA-Z0-9._-]/g,'_');const path=`${jobId}/${crypto.randomUUID()}-${safe}`;const{error}=await supabase.storage.from('knt-job-evidence').upload(path,file,{upsert:false,contentType:file.type||undefined});if(error)throw error;return path}
export async function attachJobSource(jobId,file){const path=await uploadJobFile(jobId,file);return updateJob(jobId,{source_document_path:path,source_document_type:file.type||'image'})}export async function attachSignature(jobId,file){const path=await uploadJobFile(jobId,file);return updateJob(jobId,{customer_signature_path:path})}export async function getPrivateFileUrl(path,expiresIn=3600){requireCloud();if(!path)return'';const{data,error}=await supabase.storage.from('knt-job-evidence').createSignedUrl(path,expiresIn);if(error)throw error;return data?.signedUrl||''}

const validateMoneyFields=(input,fields)=>{for(const[label,value]of fields)if(value!==undefined&&value!==null&&value!==''&&(!Number.isFinite(Number(value))||Number(value)<0))throw new Error(`${label} must be a valid non-negative number.`)};export const listQuotes=()=>rows('quotes',q=>q.select('*, customers(name)').order('created_at',{ascending:false}));export const createQuote=async input=>{validateMoneyFields(input,[['Quote subtotal',input?.subtotal],['Quote VAT',input?.vat],['Quote total',input?.total]]);return one('quotes',input)};export const updateQuote=async(id,input)=>{validateMoneyFields(input,[['Quote subtotal',input?.subtotal],['Quote VAT',input?.vat],['Quote total',input?.total]]);return update('quotes',id,input)};export const getQuote=id=>single('quotes',q=>q.select('*, customers(name)').eq('id',id));export const listQuoteLines=quoteId=>rows('quote_lines',q=>q.select('*').eq('quote_id',quoteId).order('created_at'));export const createQuoteLine=async input=>{validateLineNumbers(input,'Quote line');return one('quote_lines',input)};