-- KNT Hire & Sales production foundation
-- Run in a new Supabase project before enabling the cloud data layer.
create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default '',
  role text not null default 'engineer' check (role in ('engineer','admin')),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table if not exists public.customers (id uuid primary key default gen_random_uuid(), name text not null, account_number text, phone text, email text, notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.sites (id uuid primary key default gen_random_uuid(), customer_id uuid not null references public.customers(id) on delete restrict, name text not null, address text, contact_name text, contact_phone text, contact_email text, notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.forklifts (id uuid primary key default gen_random_uuid(), customer_id uuid references public.customers(id) on delete set null, site_id uuid references public.sites(id) on delete set null, plant_number text not null unique, make text, model text, serial_number text, hours numeric, status text not null default 'active', photo_path text, next_service_date date, next_loler_date date, notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.jobs (id uuid primary key default gen_random_uuid(), job_number bigint generated by default as identity unique, customer_id uuid references public.customers(id) on delete set null, site_id uuid references public.sites(id) on delete set null, forklift_id uuid references public.forklifts(id) on delete set null, engineer_name text, engineer_user_id uuid references auth.users(id) on delete set null, status text not null default 'draft', job_date date not null default current_date, problem text, work_carried_out text, labour_hours numeric, travel numeric, customer_signature_path text, source_document_path text, source_document_type text, ai_extraction jsonb, ai_confidence jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.job_photos (id uuid primary key default gen_random_uuid(), job_id uuid not null references public.jobs(id) on delete cascade, storage_path text not null, tag text not null default 'evidence', caption text, created_at timestamptz not null default now());
create table if not exists public.job_parts (id uuid primary key default gen_random_uuid(), job_id uuid not null references public.jobs(id) on delete cascade, part_number text, description text not null, quantity numeric not null default 1, supplier text, supplier_order_number text, unit_cost numeric, status text not null default 'used', created_at timestamptz not null default now());

create table if not exists public.service_events (id uuid primary key default gen_random_uuid(), forklift_id uuid not null references public.forklifts(id) on delete cascade, job_id uuid references public.jobs(id) on delete set null, event_type text not null default 'service', event_date date not null default current_date, hours numeric, summary text, next_due_date date, engineer_user_id uuid references auth.users(id) on delete set null, created_at timestamptz not null default now());
create table if not exists public.forklift_documents (id uuid primary key default gen_random_uuid(), forklift_id uuid not null references public.forklifts(id) on delete cascade, document_type text not null, title text not null, storage_path text not null, issue_date date, expiry_date date, notes text, created_at timestamptz not null default now());
create table if not exists public.suppliers (id uuid primary key default gen_random_uuid(), name text not null, account_number text, phone text, email text, notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.parts (id uuid primary key default gen_random_uuid(), supplier_id uuid references public.suppliers(id) on delete set null, part_number text, description text not null, default_unit_cost numeric, default_sell_price numeric, active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.supplier_orders (id uuid primary key default gen_random_uuid(), supplier_id uuid references public.suppliers(id) on delete set null, order_number text not null, order_date date, status text not null default 'received', source_document_path text, notes text, created_at timestamptz not null default now(), unique(supplier_id, order_number));
create table if not exists public.supplier_order_lines (id uuid primary key default gen_random_uuid(), supplier_order_id uuid not null references public.supplier_orders(id) on delete cascade, part_id uuid references public.parts(id) on delete set null, part_number text, description text not null, quantity numeric not null default 1, unit_cost numeric, job_id uuid references public.jobs(id) on delete set null, created_at timestamptz not null default now());

create table if not exists public.pricing_settings (id uuid primary key default gen_random_uuid(), labour_rate numeric not null default 0, travel_rate numeric not null default 0, parts_markup_percent numeric not null default 0, vat_percent numeric not null default 20, active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.quotes (id uuid primary key default gen_random_uuid(), quote_number bigint generated by default as identity unique, customer_id uuid references public.customers(id) on delete set null, site_id uuid references public.sites(id) on delete set null, job_id uuid references public.jobs(id) on delete set null, status text not null default 'draft', quote_date date not null default current_date, valid_until date, notes text, subtotal numeric not null default 0, vat numeric not null default 0, total numeric not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.quote_lines (id uuid primary key default gen_random_uuid(), quote_id uuid not null references public.quotes(id) on delete cascade, description text not null, quantity numeric not null default 1, unit_price numeric not null default 0, vat_rate numeric not null default 20, created_at timestamptz not null default now());
create table if not exists public.invoices (id uuid primary key default gen_random_uuid(), invoice_number bigint generated by default as identity unique, customer_id uuid references public.customers(id) on delete set null, job_id uuid references public.jobs(id) on delete set null, quote_id uuid references public.quotes(id) on delete set null, status text not null default 'awaiting_review', invoice_date date not null default current_date, due_date date, subtotal numeric not null default 0, vat numeric not null default 0, total numeric not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.invoice_lines (id uuid primary key default gen_random_uuid(), invoice_id uuid not null references public.invoices(id) on delete cascade, description text not null, quantity numeric not null default 1, unit_price numeric not null default 0, vat_rate numeric not null default 20, created_at timestamptz not null default now());
create table if not exists public.payments (id uuid primary key default gen_random_uuid(), invoice_id uuid not null references public.invoices(id) on delete cascade, payment_date date not null default current_date, amount numeric not null, reference text, notes text, created_at timestamptz not null default now());
create table if not exists public.reminders (id uuid primary key default gen_random_uuid(), forklift_id uuid references public.forklifts(id) on delete cascade, job_id uuid references public.jobs(id) on delete cascade, reminder_type text not null, due_date date not null, status text not null default 'open', reminder_days integer[] not null default '{60,30,14,7}', created_at timestamptz not null default now());
create table if not exists public.job_status_history (id uuid primary key default gen_random_uuid(), job_id uuid not null references public.jobs(id) on delete cascade, old_status text, new_status text not null, changed_by uuid references auth.users(id) on delete set null, changed_at timestamptz not null default now(), note text);

create index if not exists sites_customer_id_idx on public.sites(customer_id);
create index if not exists forklifts_site_id_idx on public.forklifts(site_id);
create index if not exists forklifts_serial_idx on public.forklifts(serial_number);
create index if not exists jobs_forklift_id_idx on public.jobs(forklift_id);
create index if not exists jobs_job_date_idx on public.jobs(job_date desc);
create index if not exists job_photos_job_id_idx on public.job_photos(job_id);
create index if not exists job_parts_job_id_idx on public.job_parts(job_id);
create index if not exists service_events_forklift_id_idx on public.service_events(forklift_id);
create index if not exists forklift_documents_forklift_id_idx on public.forklift_documents(forklift_id);
create index if not exists supplier_order_lines_job_id_idx on public.supplier_order_lines(job_id);
create index if not exists invoices_customer_id_idx on public.invoices(customer_id);
create index if not exists reminders_due_date_idx on public.reminders(due_date);
create index if not exists job_status_history_job_id_idx on public.job_status_history(job_id, changed_at desc);

create or replace function public.set_updated_at() returns trigger language plpgsql as $$ begin new.updated_at = now(); return new; end $$;
do $$ declare t text; begin foreach t in array array['profiles','customers','sites','forklifts','jobs','suppliers','parts','pricing_settings','quotes','invoices'] loop execute format('drop trigger if exists %I_updated_at on public.%I', t, t); execute format('create trigger %I_updated_at before update on public.%I for each row execute function public.set_updated_at()', t, t); end loop; end $$;

alter table public.profiles enable row level security;
alter table public.customers enable row level security;
alter table public.sites enable row level security;
alter table public.forklifts enable row level security;
alter table public.jobs enable row level security;
alter table public.job_photos enable row level security;
alter table public.job_parts enable row level security;
alter table public.service_events enable row level security;
alter table public.forklift_documents enable row level security;
alter table public.suppliers enable row level security;
alter table public.parts enable row level security;
alter table public.supplier_orders enable row level security;
alter table public.supplier_order_lines enable row level security;
alter table public.pricing_settings enable row level security;
alter table public.quotes enable row level security;
alter table public.quote_lines enable row level security;
alter table public.invoices enable row level security;
alter table public.invoice_lines enable row level security;
alter table public.payments enable row level security;
alter table public.reminders enable row level security;
alter table public.job_status_history enable row level security;

-- Shared KNT workspace: authenticated engineers can work with shared operational records.
do $$ declare t text; begin foreach t in array array['customers','sites','forklifts','jobs','job_photos','job_parts','service_events','forklift_documents','suppliers','parts','supplier_orders','supplier_order_lines','pricing_settings','quotes','quote_lines','invoices','invoice_lines','payments','reminders','job_status_history'] loop execute format('drop policy if exists "authenticated shared access" on public.%I', t); execute format('create policy "authenticated shared access" on public.%I for all to authenticated using (true) with check (true)', t); end loop; end $$;
create policy "users can read own profile" on public.profiles for select to authenticated using (id = auth.uid());
create policy "users can update own profile" on public.profiles for update to authenticated using (id = auth.uid()) with check (id = auth.uid());
