-- KNT Hire & Sales production foundation
-- Run in a new Supabase project before enabling the cloud data layer.

create extension if not exists pgcrypto;

create table if not exists public.customers (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  account_number text,
  phone text,
  email text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.sites (
  id uuid primary key default gen_random_uuid(),
  customer_id uuid not null references public.customers(id) on delete restrict,
  name text not null,
  address text,
  contact_name text,
  contact_phone text,
  contact_email text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.forklifts (
  id uuid primary key default gen_random_uuid(),
  customer_id uuid references public.customers(id) on delete set null,
  site_id uuid references public.sites(id) on delete set null,
  plant_number text not null unique,
  make text,
  model text,
  serial_number text,
  hours numeric,
  status text not null default 'active',
  photo_path text,
  next_service_date date,
  next_loler_date date,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.jobs (
  id uuid primary key default gen_random_uuid(),
  job_number bigint generated by default as identity unique,
  customer_id uuid references public.customers(id) on delete set null,
  site_id uuid references public.sites(id) on delete set null,
  forklift_id uuid references public.forklifts(id) on delete set null,
  engineer_name text,
  engineer_user_id uuid references auth.users(id) on delete set null,
  status text not null default 'draft',
  job_date date not null default current_date,
  problem text,
  work_carried_out text,
  labour_hours numeric,
  travel numeric,
  customer_signature_path text,
  source_document_path text,
  source_document_type text,
  ai_extraction jsonb,
  ai_confidence jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.job_photos (
  id uuid primary key default gen_random_uuid(),
  job_id uuid not null references public.jobs(id) on delete cascade,
  storage_path text not null,
  tag text not null default 'evidence',
  caption text,
  created_at timestamptz not null default now()
);

create table if not exists public.job_parts (
  id uuid primary key default gen_random_uuid(),
  job_id uuid not null references public.jobs(id) on delete cascade,
  part_number text,
  description text not null,
  quantity numeric not null default 1,
  supplier text,
  supplier_order_number text,
  unit_cost numeric,
  status text not null default 'used',
  created_at timestamptz not null default now()
);

create index if not exists sites_customer_id_idx on public.sites(customer_id);
create index if not exists forklifts_site_id_idx on public.forklifts(site_id);
create index if not exists forklifts_serial_idx on public.forklifts(serial_number);
create index if not exists jobs_forklift_id_idx on public.jobs(forklift_id);
create index if not exists jobs_job_date_idx on public.jobs(job_date desc);
create index if not exists job_photos_job_id_idx on public.job_photos(job_id);
create index if not exists job_parts_job_id_idx on public.job_parts(job_id);

alter table public.customers enable row level security;
alter table public.sites enable row level security;
alter table public.forklifts enable row level security;
alter table public.jobs enable row level security;
alter table public.job_photos enable row level security;
alter table public.job_parts enable row level security;

-- Two authenticated KNT engineers share the same cloud workspace.
-- Fine-grained production policies can be tightened when user roles are added.
create policy "authenticated users can manage customers" on public.customers for all to authenticated using (true) with check (true);
create policy "authenticated users can manage sites" on public.sites for all to authenticated using (true) with check (true);
create policy "authenticated users can manage forklifts" on public.forklifts for all to authenticated using (true) with check (true);
create policy "authenticated users can manage jobs" on public.jobs for all to authenticated using (true) with check (true);
create policy "authenticated users can manage job photos" on public.job_photos for all to authenticated using (true) with check (true);
create policy "authenticated users can manage job parts" on public.job_parts for all to authenticated using (true) with check (true);
