#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import {execFileSync,spawn} from 'node:child_process';
import {appendAudit} from '../quality/audit-log.mjs';
const root=process.cwd(),minutes=Number.parseInt(process.env.BUILDER_MAX_MINUTES||'15',10),model=process.env.LOCAL_AI_MODEL||'qwen2.5-coder:7b',host=process.env.OLLAMA_HOST||'http://127.0.0.1:11434';
const timeout=Math.max(90,Number.parseInt(process.env.LOCAL_AI_FEATURE_TIMEOUT_SECONDS||'210',10));const maxAttempts=Math.max(1,Number.parseInt(process.env.AUTOBOT_FEATURE_MAX_ATTEMPTS||'2',10));const maxEdits=Math.max(1,Math.min(3,Number.parseInt(process.env.AUTOBOT_FEATURE_MAX_EDITS||'2',10)));const started=Date.now();const left=()=>Math.max(0,minutes-(Date.now()-started)/60000);const abs=p=>path.join(root,p);const run=(c,a,o={})=>execFileSync(c,a,{cwd:root,encoding:'utf8',...o});const read=p=>{try{return fs.readFileSync(abs(p),'utf8')}catch{return''}};
const objectives=JSON.parse(read('builder/brain/feature-objectives.json')).objectives||[];const statePath=abs('builder/working/feature-brain-state.json');let state={completed:[],failed:{}};try{state=JSON.parse(fs.readFileSync(statePath,'utf8'))}catch{}const completed=new Set(state.completed||[]);const attempts=new Map();
function save(){fs.mkdirSync(path.dirname(statePath),{recursive:true});fs.writeFileSync(statePath,JSON.stringify({version:1,completed:[...completed],failed:state.failed||{},updatedAt:new Date().toISOString()},null,2)+'\n')}
function deps(o){return(o.dependsOn||[]).every(d=>completed.has(d)||!objectives.some(x=>x.id===d))}
function choose(){const available=objectives.filter(o=>!completed.has(o.id)&&deps(o)&&(attempts.get(o.id)||0)<maxAttempts);return available.sort((a,b)=>(b.priority||0)-(a.priority||0))[0]||null}
function sourceContext(o){const map=(()=>{try{return JSON.parse(read('builder/working/repository-map.json'))}catch{return{byPath:{}}}})();return(o.files||[]).map(p=>{const s=read(p);const lines=s.split(/\r?\n/);const symbols=(map.byPath?.[p]?.symbols||[]).slice(0,12);let text=lines.slice(0,20).map((x,i)=>`${i+1}| ${x}`).join('\n');if(lines.length>45)text+='\n...\n'+lines.slice(-20).map((x,i)=>`${lines.length-19+i}| ${x}`).join('\n');return`===== ${p} =====\n${text}\nSYMBOLS: ${symbols.join(', ')}`}).join('\n\n')}
function prompt(o,repair){const failure=state.failed?.[o.id];return`You are the local Qwen implementation engineer for KNT Hire & Sales, a forklift service business app. Make ONE small, production-quality increment for this objective. Modify ONLY the listed product files. Never modify workflows, builder infrastructure, secrets, deployment config or dependencies. Never fabricate OCR/AI data. Preserve original paper evidence and never auto-send invoices.\n\nOBJECTIVE: ${o.title}\nAcceptance:\n- ${(o.acceptance||[]).join('\n- ')}\nConstraints:\n- ${(o.constraints||[]).join('\n- ')}\n\nEDIT PROTOCOL: Return ONLY JSON: {"edits":[{"file":"...","search":"...","replace":"..."}]}. At most ${maxEdits} edits. SEARCH must be copied literally from supplied source and occur exactly once. Prefer a small nearby block. Do not rewrite entire files, use markdown, diffs, line numbers or placeholders. ${repair?`Previous attempt failed. Fix the specific failure and choose a different anchor if necessary. Evidence: ${JSON.stringify(failure).slice(0,5000)}`:'Choose the smallest change that clearly advances an acceptance criterion.'}\n\n${sourceContext(o)}\n\nPROJECT MEMORY:\n${read('builder/quality/project-memory.md').slice(0,1800)}\n\nLESSONS:\n${read('builder/quality/lessons.md').slice(0,1400)}`}
function callModel(o,repair){const body=JSON.stringify({model,stream:false,format:{type:'object',additionalProperties:false,properties:{edits:{type:'array',minItems:1,maxItems:maxEdits,items:{type:'object',additionalProperties:false,properties:{file:{type:'string'},search:{type:'string',minLength:1,maxLength:2600},replace:{type:'string',maxLength:4000}},required:['file','search','replace']}}},required:['edits']},options:{temperature:0,num_ctx:16384,num_predict:2600},messages:[{role:'system',content:'Senior JavaScript/React engineer. Output only valid JSON search-replace edits.'},{role:'user',content:prompt(o,repair)}]});return new Promise((resolve,reject)=>{const sec=Math.min(timeout,Math.max(60,Math.floor(left()*60)));const child=spawn('curl',['-sS','--fail','--connect-timeout','15','--max-time',String(sec),`${host}/api/chat`,'-H','Content-Type: application/json','-d',body],{cwd:root});let out='',err='';const timer=setTimeout(()=>{try{child.kill('SIGTERM')}catch{}reject(new Error(`Qwen request timed out after ${sec}s`))},sec*1000+2000);child.stdout.on('data',d=>out+=d);child.stderr.on('data',d=>err+=d);child.on('error',reject);child.on('close',code=>{clearTimeout(timer);if(code!==0)return reject(new Error(err||`Qwen failed (${code})`));try{const lines=out.split(/\r?\n/).filter(Boolean);let content='';for(const l of lines){try{const j=JSON.parse(l);if(j.message?.content)content=j.message.content}catch{}}resolve(JSON.parse(content))}catch(e){reject(new Error(`Qwen structured JSON parse failed: ${e.message}`))}})})}
function validate(payload,o){if(!payload?.edits?.length||payload.edits.length>maxEdits)throw Error('invalid edit list');const allowed=new Set(o.files||[]),seen=new Set();for(const e of payload.edits){if(!allowed.has(e.file))throw Error(`out-of-scope file: ${e.file}`);if(seen.has(e.file))throw Error(`multiple edits in ${e.file} disabled`);seen.add(e.file);const s=read(e.file),count=s.split(e.search).length-1;if(count!==1)throw Error(`search must match exactly once in ${e.file}; found ${count}`);if(e.search.length>2600||e.replace.length>4000)throw Error('edit too large')}}
function apply(payload){for(const e of payload.edits){const p=abs(e.file),s=fs.readFileSync(p,'utf8');fs.writeFileSync(p,s.replace(e.search,e.replace))}}
function reset(){run('git',['reset','--hard','HEAD']);run('git',['clean','-fd','-e','.git'])}
function verify(){run('git',['diff','--check']);for(const p of run('git',['diff','--name-only','--diff-filter=ACM']).split(/\r?\n/).filter(Boolean).filter(p=>/\.(js|mjs|cjs|jsx|ts|tsx)$/.test(p)))run(process.execPath,['--check',p]);run('npm',['run','build'],{timeout:Math.min(900000,Math.max(60000,Math.floor(left()*60000)))})}
if(process.env.LOCAL_AI_READY!=='1'){console.error('[autobot] LOCAL_AI_READY is not 1');process.exit(2)}
run(process.execPath,['scripts/autobot/repository-intelligence.mjs']);appendAudit('knt-feature-run-started',{minutes,model,maxAttempts,maxEdits});
const obj=choose();if(!obj){console.log('[autobot] no eligible KNT objective available');process.exit(0)}
for(let attempt=1;attempt<=maxAttempts&&left()>1;attempt++){attempts.set(obj.id,attempt);console.log(`[autobot] KNT ${obj.id} attempt ${attempt}/${maxAttempts}; ${left().toFixed(1)}m left; model=${model}`);try{const payload=await callModel(obj,attempt>1);validate(payload,obj);apply(payload);verify();completed.add(obj.id);delete state.failed[obj.id];save();appendAudit('knt-feature-verified',{objectiveId:obj.id,attempt});console.log(`[autobot] VERIFIED ${obj.id}`);process.exit(0)}catch(e){const diff=(()=>{try{return run('git',['diff']).slice(0,7000)}catch{return''}})();state.failed[obj.id]={attempts:(state.failed[obj.id]?.attempts||0)+1,class:String(e.message).slice(0,120),message:String(e.message).slice(0,3000),diff};save();appendAudit('knt-feature-attempt-failed',{objectiveId:obj.id,attempt,error:String(e.message).slice(0,1500)});reset()}}
process.exit(1);
