import { Sandbox } from '@vercel/sandbox';
import { mkdir, writeFile } from 'node:fs/promises';

const REPO_URL=process.env.BUILDER_REPO_URL||'https://github.com/bikeztagram-ai/KNT-HIRE-AND-SALES.git';
const BATCH_ID=process.env.BUILDER_BATCH_ID||`knt-${Date.now()}`;
const BRANCH=process.env.BUILDER_WORKING_BRANCH||`autonomous-builder/${BATCH_ID}`;
const BASE_BRANCH=process.env.BUILDER_BASE_BRANCH||'feature/knt-v1-foundation';
const MAX_MINUTES=Math.max(15,Math.min(Number(process.env.BUILDER_MAX_MINUTES||120),120));
const MAX_PASSES=Math.max(1,Math.min(Number(process.env.BUILDER_MAX_PASSES||8),8));
const ROOT='/vercel/sandbox',REPO_DIR=`${ROOT}/repo`,ASKPASS=`${ROOT}/git-askpass.sh`;
const PROTECTED=(process.env.BUILDER_PROTECTED_PATHS||'.github/workflows/,builder/runner/').split(',').map(x=>x.trim()).filter(Boolean);
// Pin the known-good CLI for the sandbox worker. Codex 0.150.x introduced
// exec-mode regressions and changed/deprecated automation flags; 0.149.1 is
// retained here until a newer release is explicitly smoke-tested in CI.
const AGENT_CMD=process.env.BUILDER_AGENT_CMD?JSON.parse(process.env.BUILDER_AGENT_CMD):['npx','--yes','@openai/codex@0.149.1','exec','--full-auto'];
const OBJECTIVE=process.env.BUILDER_OBJECTIVE||'Execute the highest-priority ready objective from config/autonomous-builder-queue.json and continue through coherent KNT work until the run budget is exhausted.';
const VERIFY_COMMANDS=(process.env.BUILDER_VERIFY_COMMANDS||'npm run build').split(',').map(x=>x.trim()).filter(Boolean);
const COMMAND_TIMEOUT_MS=Math.max(60_000,Math.min(Number(process.env.BUILDER_COMMAND_TIMEOUT_MS||18*60*1000),MAX_MINUTES*60*1000));
const results=[];const compact=(v,n=12000)=>{const s=String(v||'').trim();return s.length<=n?s:`${s.slice(0,n)}\n...[truncated]`};
const shellQuote=v=>`'${String(v).replace(/'/g,"'\\''")}'`;const text=r=>`${r?.stdout||''}\n${r?.stderr||''}`.toLowerCase();
const quota=r=>/quota|rate limit|too many requests|resource exhausted|\b429\b|usage limit|credit.*depleted|billing/.test(text(r));
const provider=r=>/model .*not found|invalid model|api key|authentication|unauthenticated|permission denied|forbidden|\b401\b|\b403\b|\b404\b/.test(text(r));
const safeBranch=b=>b&&!['main','master'].includes(b)&&!b.startsWith('production/');const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function run(s,cmd,args=[],cwd=REPO_DIR,env){const r=await s.runCommand({cmd,args,cwd,...(env?{env}:{}),signal:AbortSignal.timeout(COMMAND_TIMEOUT_MS)});const o={command:[cmd,...args].join(' '),exitCode:r.exitCode,stdout:compact(await r.stdout()),stderr:compact(await r.stderr())};results.push(o);return o}
async function agent(s,prompt,env,pass){const stamp=`${BATCH_ID}-${pass}-${Date.now()}`,log=`/tmp/knt-agent-${stamp}.log`,exit=`/tmp/knt-agent-${stamp}.exit`,args=[...AGENT_CMD.slice(1),prompt],line=[AGENT_CMD[0],...args].map(shellQuote).join(' ');const launch=await run(s,'sh',['-lc',`rm -f ${shellQuote(log)} ${shellQuote(exit)}; nohup sh -lc ${shellQuote(`${line} > ${shellQuote(log)} 2>&1; c=$?; printf '%s' \"$c\" > ${shellQuote(exit)}`)} >/dev/null 2>&1 &`],ROOT,env);if(launch.exitCode)return launch;const started=Date.now();let last='';while(Date.now()-started<COMMAND_TIMEOUT_MS){const p=await run(s,'sh',['-lc',`test -f ${shellQuote(exit)} && cat ${shellQuote(exit)} || printf RUNNING`]);if(p.exitCode===0&&p.stdout.trim()!=='RUNNING'){const l=await run(s,'cat',[log]);return{command:line,exitCode:Number(p.stdout.trim())||1,stdout:compact(l.stdout),stderr:compact(l.stderr)}}const t=await run(s,'tail',['-n','12',log]);if(t.stdout.trim()&&t.stdout.trim()!==last){last=t.stdout.trim();console.log(`[KNT AutoBot] pass ${pass}:\n${compact(last,4000)}`)}await sleep(5000)}return{command:line,exitCode:124,stdout:last,stderr:'Agent command timeout'} }
async function verify(s){const failures=[];const d=await run(s,'git',['diff','--check']);if(d.exitCode)failures.push('git diff --check failed');for(const spec of VERIFY_COMMANDS){const [cmd,...args]=spec.split(/\s+/),r=await run(s,cmd,args);if(r.exitCode)failures.push(`${spec} failed: ${compact(r.stderr||r.stdout)}`)}return failures}
async function protect(s){const st=await run(s,'git',['status','--short']);const changed=st.stdout.split('\n').filter(Boolean).map(x=>x.replace(/^[MADRCU?!]{1,2}\s+/,'').trim());const blocked=changed.filter(p=>PROTECTED.some(x=>p===x||p.startsWith(x)));for(const p of PROTECTED){await run(s,'git',['restore','--source=HEAD','--staged','--worktree','--',p]);await run(s,'git',['clean','-fd','--',p])}return blocked}
async function publish(s,env){await run(s,'git',['config','user.name','KNT Autonomous Builder']);await run(s,'git',['config','user.email','41898282+github-actions[bot]@users.noreply.github.com']);await run(s,'git',['add','-A']);const c=await run(s,'git',['commit','-m',`builder: complete ${BATCH_ID}`]);if(c.exitCode)throw Error(c.stderr||'commit failed');const sha=(await run(s,'git',['rev-parse','HEAD'])).stdout.trim();const f=await run(s,'git',['fetch','origin',`${BRANCH}:refs/remotes/origin/${BRANCH}`],REPO_DIR,env);const p=await run(s,'git',f.exitCode===0?['push','--force-with-lease','--set-upstream','origin',`HEAD:${BRANCH}`]:['push','--set-upstream','origin',`HEAD:${BRANCH}`],REPO_DIR,env);if(p.exitCode)throw Error(p.stderr||'push failed');return sha}
function prompt(pass,failures){return[`KNT HIRE & SALES AUTONOMOUS ENGINEERING WORKER — ${BATCH_ID}`,'You are an execution worker for KNT Hire & Sales only.','Before coding, read builder/quality/project-memory.md, builder/quality/lessons.md and config/autonomous-builder-queue.json.','Select the highest-priority READY objective that is not already satisfied. Work on that objective and, if it becomes verified, continue to the next compatible ready objective in this same run.','Do not wait for user input. Diagnose and repair failures yourself whenever possible.','Make substantive production changes, integrate with existing contracts, and run verification after each coherent unit.','Never fabricate OCR/AI. Preserve original paper evidence. Never auto-send invoices.','Do not modify .github/workflows/**, builder/runner/**, or production deployment. Never merge. Never push.','PASS '+pass+'/'+MAX_PASSES,failures.length?`Previous verification failures:\n${failures.join('\n')}`:'',`RUN OBJECTIVE: ${OBJECTIVE}`].join('\n')}
async function main(){if(!safeBranch(BRANCH))throw Error(`Unsafe branch ${BRANCH}`);if(!process.env.GITHUB_TOKEN)throw Error('GITHUB_TOKEN required');if(!process.env.OPENAI_API_KEY)throw Error('OPENAI_API_KEY required');if(!process.env.VERCEL_TOKEN||!process.env.VERCEL_TEAM_ID||!process.env.VERCEL_PROJECT_ID)throw Error('Vercel sandbox credentials required');let s,failures=[],status='FAILED',sha=null,passes=0;const env={GITHUB_TOKEN:process.env.GITHUB_TOKEN,GIT_ASKPASS:ASKPASS,GIT_TERMINAL_PROMPT:'0'};const startedAt=new Date().toISOString();try{s=await Sandbox.create({teamId:process.env.VERCEL_TEAM_ID,projectId:process.env.VERCEL_PROJECT_ID,token:process.env.VERCEL_TOKEN,runtime:'node24',resources:{vcpus:4},persistent:false,timeout:MAX_MINUTES*60*1000,networkPolicy:'allow-all'});await run(s,'sh',['-lc',`cat > ${shellQuote(ASKPASS)} <<'EOF'\n#!/bin/sh\ncase "$1" in *Username*) printf '%s\\n' x-access-token;; *) printf '%s\\n' "$GITHUB_TOKEN";; esac\nEOF\nchmod 700 ${shellQuote(ASKPASS)}`],ROOT,env);let r=await run(s,'git',['clone','--branch',BASE_BRANCH,'--depth','1',REPO_URL,REPO_DIR],ROOT,env);if(r.exitCode)throw Error(`clone failed: ${r.stderr}`);r=await run(s,'git',['checkout','-b',BRANCH]);if(r.exitCode)throw Error(`branch failed: ${r.stderr}`);r=await run(s,'npm',['install','--no-audit','--no-fund','--no-package-lock']);if(r.exitCode)throw Error(`install failed: ${r.stderr||r.stdout}`);for(passes=1;passes<=MAX_PASSES;passes++){const a=await agent(s,prompt(passes,failures),{OPENAI_API_KEY:process.env.OPENAI_API_KEY},passes);if(quota(a)||provider(a)||a.exitCode){failures=[quota(a)?'Provider quota/rate limit reached':provider(a)?'Provider/model/authentication failure':`Agent failed with exit ${a.exitCode}`];break}const st=await run(s,'git',['status','--short']);if(!st.stdout.trim()){failures=['No repository changes produced'];break}await protect(s);failures=await verify(s);if(failures.length)continue;status='VERIFIED';sha=await publish(s,env);break} }catch(e){failures=[e?.message||String(e)]}finally{if(s)await s.stop().catch(()=>{})}const report={batchId:BATCH_ID,status,startedAt,finishedAt:new Date().toISOString(),passes,commitSha:sha,maxMinutes:MAX_MINUTES,maxPasses:MAX_PASSES,failures,commands:results};await mkdir('/tmp/builder-report',{recursive:true});await writeFile(`/tmp/builder-report/${BATCH_ID}.json`,JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));if(status!=='VERIFIED')process.exitCode=1}
main().catch(e=>{console.error(e);process.exitCode=1});
