import React, { useEffect, useMemo, useState } from 'react';
import { Camera, ClipboardList, Clock3, FileText, HelpCircle, Home, LogOut, Mic, MoreHorizontal, Plus, Search, Truck, Wrench, X } from 'lucide-react';
import NewJobPage from './NewJobPage';
import JobDetailPage from './JobDetailPage';
import { listForklifts, listJobs } from './lib/data';
import { signOut } from './lib/auth';
import { supabase } from './lib/supabase';
const demoJobs=[{id:'8371',customer:'ABC Manufacturing',site:'Hull Factory',plant:'1042',machine:'Toyota 8FG25',fault:'Emergency stop fault',status:'Completed',engineer:'Mike'},{id:'8368',customer:'XYZ Logistics',site:'Beverley Warehouse',plant:'1048',machine:'Linde H25D',fault:'Routine service',status:'Awaiting parts',engineer:'Dave'},{id:'8362',customer:'Northside Distribution',site:'Hull Depot',plant:'1051',machine:'Toyota 8FG30',fault:'Hydraulic leak',status:'In progress',engineer:'Mike'}];
const demoFleet=[{plant:'1042',machine:'Toyota 8FG25',customer:'ABC Manufacturing',site:'Hull Factory',hours:'8,421',due:'Service 10 Dec'},{plant:'1048',machine:'Linde H25D',customer:'ABC Manufacturing',site:'Beverley Warehouse',hours:'6,210',due:'Service 2 Oct'}];
function normaliseJob(j){return {...j,id:j.job_number??j.id,customer:j.customers?.name||'No customer',site:j.sites?.name||'No site',plant:j.forklifts?.plant_number||'No plant',machine:[j.forklifts?.make,j.forklifts?.model].filter(Boolean).join(' ')||'Forklift',fault:j.problem||'No fault recorded',engineer:j.engineer_name||'Unassigned',status:j.status?j.status.replaceAll('_',' '):'draft'}}
function normaliseFleet(f){const service=f.next_service_date?`Service ${new Date(f.next_service_date+'T00:00:00').toLocaleDateString('en-GB',{day:'numeric',month:'short'})}`:'Service not set';return{plant:f.plant_number,machine:[f.make,f.model].filter(Boolean).join(' ')||'Forklift',customer:f.customers?.name||'No customer',site:f.sites?.name||'No site',hours:Number(f.hours||0).toLocaleString('en-GB'),due:service,id:f.id}}
export default function App(){const[page,setPage]=useState('home'),[composer,setComposer]=useState(false),[search,setSearch]=useState(''),[selectedJob,setSelectedJob]=useState(null),[jobs,setJobs]=useState(demoJobs),[fleet,setFleet]=useState(demoFleet),[loading,setLoading]=useState(Boolean(supabase)),[error,setError]=useState('');const refresh=async()=>{if(!supabase)return;setLoading(true);setError('');try{const[j,f]=await Promise.all([listJobs(),listForklifts()]);setJobs(j.map(normaliseJob));setFleet(f.map(normaliseFleet))}catch(e){setError(e.message||'Could not load KNT data.')}finally{setLoading(false)}};useEffect(()=>{refresh()},[]);const navigate=p=>{setComposer(false);setPage(p);if(p==='home'||p==='jobs'||p==='fleet')refresh()};const openJob=id=>{setSelectedJob(id);setPage('job')};return <div className="app-shell"><header className="topbar"><div className="brand"><div className="brand-mark">KNT</div><div><div className="brand-name">Hire & Sales</div><div className="brand-sub">Keeping Your Business Moving</div></div></div><Help title="Using KNT Hire & Sales">Jobs can be created from a handwritten photo, voice, or normal typing. Original source documents stay attached to the record.</Help></header><main className="content">{error&&<div className="error-box" role="alert">{error}<button className="text-btn" onClick={refresh}>Retry</button></div>}{loading&&<div className="loading-bar">Loading shared KNT data…</div>}{page==='home'&&<HomePage jobs={jobs} fleet={fleet} navigate={navigate} openJob={openJob}/>} {page==='jobs'&&<JobsPage jobs={jobs} search={search} setSearch={setSearch} navigate={navigate} openJob={openJob}/>} {page==='new-job'&&<NewJobPage onBack={()=>navigate('home')} onSaved={()=>navigate('jobs')}/>} {page==='job'&&selectedJob&&<JobDetailPage jobId={selectedJob} onBack={()=>navigate('jobs')}/>} {page==='fleet'&&<FleetPage fleet={fleet}/>} {page==='more'&&<MorePage navigate={navigate}/>} {page==='help'&&<HelpPage/>}</main>{composer&&<div className="quick-menu"><button onClick={()=>navigate('new-job')}><ClipboardList size={20}/>Type job</button><button onClick={()=>navigate('new-job')}><Mic size={20}/>Voice job</button><button onClick={()=>navigate('new-job')}><Camera size={20}/>Scan paper</button></div>}{page!=='new-job'&&<nav className="bottom-nav"><NavItem active={page==='home'} icon={<Home size={20}/>} label="Home" onClick={()=>navigate('home')}/><NavItem active={page==='jobs'} icon={<ClipboardList size={20}/>} label="Jobs" onClick={()=>navigate('jobs')}/><button className="fab" aria-label="New job" onClick={()=>setComposer(v=>!v)}><Plus size={28}/></button><NavItem active={page==='fleet'} icon={<Truck size={20}/>} label="Fleet" onClick={()=>navigate('fleet')}/><NavItem active={page==='more'} icon={<MoreHorizontal size={20}/>} label="More" onClick={()=>navigate('more')}/></nav>}</div>}
function NavItem({active,icon,label,onClick}){return <button className={`nav-item ${active?'active':''}`} onClick={onClick}>{icon}<span>{label}</span></button>}
function HomePage({jobs,fleet,navigate,openJob}){const open=jobs.filter(j=>!['completed','cancelled'].includes(j.status.toLowerCase())).length;return <><section className="welcome"><div><p className="eyebrow">KNT WORKSPACE</p><h1>Good morning</h1><p className="muted">Everything you need for today's work.</p></div><div className="avatar">K</div></section><section className="stats-grid"><Stat label="Open jobs" value={open} tone="info" icon={<ClipboardList size={18}/>}/><Stat label="Fleet" value={fleet.length} tone="success" icon={<Truck size={18}/>}/><Stat label="Overdue" value="—" tone="danger" icon={<Clock3 size={18}/>}/><Stat label="Due soon" value="—" tone="warning" icon={<Wrench size={18}/>}/></section><section className="section"><div className="section-head"><h2>Quick actions</h2><span className="hint">Fastest ways to add work</span></div><div className="action-grid"><Action icon={<Camera/>} title="Scan jobsheet" text="Photograph handwritten paper" onClick={()=>navigate('new-job')}/><Action icon={<Mic/>} title="Voice job" text="Speak and let KNT structure it" onClick={()=>navigate('new-job')}/><Action icon={<ClipboardList/>} title="New job" text="Enter it manually" onClick={()=>navigate('new-job')}/></div></section><section className="section"><div className="section-head"><h2>Recent jobs</h2><button className="text-btn" onClick={()=>navigate('jobs')}>View all</button></div>{jobs.slice(0,3).map(j=><JobCard key={j.id} job={j} onClick={()=>openJob(j.id)}/>)}</section></>}
function JobsPage({jobs,search,setSearch,navigate,openJob}){const filtered=useMemo(()=>jobs.filter(j=>`${j.id} ${j.customer} ${j.plant} ${j.machine} ${j.fault}`.toLowerCase().includes(search.toLowerCase())),[jobs,search]);return <><PageTitle title="Jobs" subtitle="Create, find and complete jobsheets"><Help title="Jobs">Search by job number, customer, plant or machine. Tap a job to see its full record and status history.</Help></PageTitle><div className="search"><Search size={19}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search jobs, customers, plant..."/></div><div className="filter-row"><button className="chip active">All</button><button className="chip">In progress</button><button className="chip">Awaiting parts</button><button className="chip">Completed</button></div><button className="primary wide new-job-button" onClick={()=>navigate('new-job')}><Plus size={18}/> New jobsheet</button><div className="job-list">{filtered.length?filtered.map(j=><JobCard key={j.id} job={j} onClick={()=>openJob(j.id)}/>):<div className="empty-state"><ClipboardList size={30}/><strong>No jobs found</strong><span>Try another search or create a new jobsheet.</span></div>}</div></>}
function FleetPage({fleet}){return <><PageTitle title="Fleet" subtitle="Every forklift, its location and history"><Help title="Fleet">Forklifts are permanent records. A truck can move between sites without losing its service, repair, photos or LOLER history.</Help></PageTitle><div className="search"><Search size={19}/><input placeholder="Search plant, serial, make or customer..."/></div>{fleet.length?fleet.map(f=><div className="fleet-card" key={f.id||f.plant}><div className="machine-icon"><Truck size={25}/></div><div className="grow"><div className="card-title">Plant {f.plant} · {f.machine}</div><div className="muted">{f.customer} · {f.site}</div><div className="meta"><span>{f.hours} hrs</span><span>{f.due}</span></div></div><span className="chevron">›</span></div>):<div className="empty-state"><Truck size={30}/><strong>No forklifts yet</strong><span>Add your first forklift when the fleet module is ready.</span></div>}</>}
function MorePage({navigate}){const logout=async()=>{if(supabase)await signOut()};return <><PageTitle title="More" subtitle="KNT tools and settings"><Help title="More">Customers, sites, parts, suppliers, service, LOLER, quotes, invoices and documents will live here.</Help></PageTitle>{['Customers & sites','Parts & suppliers','Service & LOLER','Quotes & invoices','Documents','Help & how to use'].map((item,i)=><button className="menu-row" key={item} onClick={()=>item==='Help & how to use'&&navigate('help')}><span>{[<Truck/>,<Wrench/>,<Clock3/>,<FileText/>,<FileText/>,<HelpCircle/>][i]}</span><strong>{item}</strong><span className="chevron">›</span></button>)}{supabase&&<button className="menu-row danger-row" onClick={logout}><span><LogOut/></span><strong>Sign out</strong><span className="chevron">›</span></button>}</>}
function HelpPage(){return <><PageTitle title="How to use KNT" subtitle="A simple guide for engineers"><Help title="Help">This guide will grow with the app.</Help></PageTitle><div className="help-card"><strong>📸 Scan a paper jobsheet</strong><p>Photograph the handwritten sheet. KNT will keep the original image attached.</p></div><div className="help-card"><strong>🎙️ Speak a jobsheet</strong><p>Talk normally and review the transcript before saving.</p></div><div className="help-card"><strong>⌨️ Type a jobsheet</strong><p>Use the normal digital form whenever typing is quicker.</p></div></>}
function Help({title,children}){const[open,setOpen]=useState(false);return <><button className="icon-btn" aria-label="Page help" onClick={()=>setOpen(true)}><HelpCircle size={21}/></button>{open&&<div className="modal-backdrop" onClick={()=>setOpen(false)}><div className="modal" onClick={e=>e.stopPropagation()}><div className="modal-head"><strong>{title}</strong><button className="icon-btn" onClick={()=>setOpen(false)}><X size={20}/></button></div><div className="modal-copy">{children}</div><button className="primary wide" onClick={()=>setOpen(false)}>Got it</button></div></div>}</>}
function PageTitle({title,subtitle,children}){return <div className="page-title"><div><h1>{title}</h1><p className="muted">{subtitle}</p></div>{children}</div>}
function Stat({label,value,tone,icon}){return <div className={`stat ${tone}`}><div className="stat-icon">{icon}</div><div><strong>{value}</strong><span>{label}</span></div></div>}
function Action({icon,title,text,onClick}){return <button className="action-card" onClick={onClick}><div className="action-icon">{icon}</div><div><strong>{title}</strong><span>{text}</span></div><span className="chevron">›</span></button>}
function JobCard({job,onClick}){return <button className="job-card job-card-button" onClick={onClick}><div className="job-top"><span className="job-id">JOB {job.id}</span><span className={`status ${String(job.status).toLowerCase().replaceAll(' ','-')}`}>{job.status}</span></div><div className="card-title">{job.fault}</div><div className="muted">{job.customer} · {job.site}</div><div className="meta"><span>Plant {job.plant}</span><span>{job.machine}</span><span>{job.engineer}</span></div></button>}
