import React,{useEffect,useState}from'react';import{ArrowLeft,CalendarCheck,Save,Truck,Wrench,MapPin}from'lucide-react';import{createServiceEvent,getForklift,listCustomers,listJobs,listServiceEvents,listSites,updateForklift}from'./lib/data';import{supabase}from'./lib/supabase';
export default function ForkliftDetailPage({forkliftId,onBack}){const[f,setF]=useState(null),[events,setEvents]=useState([]),[jobs,setJobs]=useState([]),[customers,setCustomers]=useState([]),[sites,setSites]=useState([]),[editing,setEditing]=useState(false),[moving,setMoving]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState(''),[form,setForm]=useState({}),[moveCustomerId,setMoveCustomerId]=useState(''),[moveSiteId,setMoveSiteId]=useState('');
const load=async()=>{try{const[x,e,j,c]=await Promise.all([getForklift(forkliftId),listServiceEvents(forkliftId),listJobs(),listCustomers()]);setF(x);setEvents(e);setJobs(j.filter(a=>a.forklift_id===forkliftId));setCustomers(c);setMoveCustomerId(x.customer_id||'');setForm({plant_number:x.plant_number||'',make:x.make||'',model:x.model||'',serial_number:x.serial_number||'',hours:x.hours??'',status:x.status||'active',next_service_date:x.next_service_date||'',next_loler_date:x.next_loler_date||'',notes:x.notes||''});if(x.customer_id)setSites(await listSites(x.customer_id));else setSites([]);setMoveSiteId(x.site_id||'')}catch(e){setError(e.message)}};
useEffect(()=>{if(supabase)load()},[forkliftId]);
useEffect(()=>{if(!moveCustomerId){setSites([]);setMoveSiteId('');return}listSites(moveCustomerId).then(setSites).catch(e=>setError(e.message))},[moveCustomerId]);
const save=async()=>{setSaving(true);try{await updateForklift(forkliftId,{...form,hours:form.hours===''?null:Number(form.hours)});setEditing(false);await load()}catch(e){setError(e.message)}finally{setSaving(false)}};
const move=async()=>{if(!moveCustomerId){setError('Select a customer before moving the forklift.');return}setSaving(true);setError('');try{await updateForklift(forkliftId,{customer_id:moveCustomerId,site_id:moveSiteId||null});setMoving(false);await load()}catch(e){setError(e.message)}finally{setSaving(false)}};
const completeService=async()=>{const date=new Date().toISOString().slice(0,10);try{await createServiceEvent({forklift_id:forkliftId,event_type:'service',event_date:date,hours:f.hours,summary:'Service completed'});await updateForklift(forkliftId,{next_service_date:null});await load()}catch(e){setError(e.message)}};
if(!supabase)return <div className="empty-state">Cloud setup required</div>;if(!f)return <div className="loading-bar">Loading forklift…</div>;
return <><div className="page-title"><div className="title-with-back"><button className="icon-btn"onClick={onBack}><ArrowLeft/></button><div><p className="eyebrow">FORKLIFT</p><h1>Plant {f.plant_number}</h1><p className="muted">{f.make} {f.model} · {f.serial_number||'No serial recorded'}</p></div></div><div className="filter-row"><button className="secondary"onClick={()=>setMoving(v=>!v)}><MapPin size={17}/>{moving?'Cancel move':'Move machine'}</button><button className="secondary"onClick={()=>setEditing(v=>!v)}>{editing?'Cancel':'Edit'}</button></div></div>{error&&<div className="error-box">{error}</div>}
<section className="detail-card"><div className="detail-grid"><div><span>Customer</span><strong>{f.customers?.name||'—'}</strong></div><div><span>Site</span><strong>{f.sites?.name||'Unassigned'}</strong></div><div><span>Hours</span><strong>{Number(f.hours||0).toLocaleString('en-GB')}</strong></div><div><span>Status</span><strong>{f.status}</strong></div><div><span>Next service</span><strong>{f.next_service_date||'Not set'}</strong></div><div><span>Next LOLER</span><strong>{f.next_loler_date||'Not set'}</strong></div></div>
{moving&&<div className="form-card"><h3>Move forklift</h3><p className="muted">The forklift's existing jobs and service history stay attached to this machine.</p><label>Customer<select value={moveCustomerId}onChange={e=>setMoveCustomerId(e.target.value)}><option value="">Select customer…</option>{customers.map(c=><option key={c.id}value={c.id}>{c.name}</option>)}</select></label><label>Site<select value={moveSiteId}onChange={e=>setMoveSiteId(e.target.value)}><option value="">No site / depot</option>{sites.map(s=><option key={s.id}value={s.id}>{s.name}</option>)}</select></label><button className="primary wide"disabled={saving}onClick={move}><MapPin size={18}/>Save new location</button></div>}
{editing&&<div className="form-grid"><label>Plant number<input value={form.plant_number}onChange={e=>setForm({...form,plant_number:e.target.value})}/></label><label>Make<input value={form.make}onChange={e=>setForm({...form,make:e.target.value})}/></label><label>Model<input value={form.model}onChange={e=>setForm({...form,model:e.target.value})}/></label><label>Serial<input value={form.serial_number}onChange={e=>setForm({...form,serial_number:e.target.value})}/></label><label>Hours<input type="number"value={form.hours}onChange={e=>setForm({...form,hours:e.target.value})}/></label><label>Status<select value={form.status}onChange={e=>setForm({...form,status:e.target.value})}><option value="active">Active</option><option value="out_of_service">Out of service</option><option value="sold">Sold</option></select></label><label>Next service<input type="date"value={form.next_service_date}onChange={e=>setForm({...form,next_service_date:e.target.value})}/></label><label>Next LOLER<input type="date"value={form.next_loler_date}onChange={e=>setForm({...form,next_loler_date:e.target.value})}/></label><label className="full">Notes<textarea value={form.notes}onChange={e=>setForm({...form,notes:e.target.value})}/></label><button className="primary wide"disabled={saving}onClick={save}><Save size={18}/>Save changes</button></div>}</section>
<section className="detail-card"><div className="section-head"><h2><Wrench size={18}/> Service history</h2><button className="secondary"onClick={completeService}><CalendarCheck size={17}/> Log service today</button></div>{events.map(e=><div className="site-row"key={e.id}><CalendarCheck size={17}/><div><strong>{e.event_type} · {e.event_date}</strong><span>{e.summary||'No summary'}{e.hours!=null?\` · \${e.hours} hrs\`:''}</span></div></div>)}{!events.length&&<p className="muted">No service events recorded yet.</p>}</section>
<section className="detail-card"><h2><Truck size={18}/> Job history</h2>{jobs.slice(0,10).map(j=><div className="site-row"key={j.id}><div><strong>Job {j.job_number}</strong><span>{j.job_date} · {j.problem||'No problem recorded'} · {j.status}</span></div></div>)}{!jobs.length&&<p className="muted">No jobs recorded for this forklift.</p>}</section></>}