import React, { useEffect, useState } from 'react';
import { ArrowLeft, CheckCircle2, Clock3, Download, Edit3, FileImage, History, Loader2, PenLine, Save, Wrench } from 'lucide-react';
import { createJobPart, getJob, listJobParts, listJobPhotos, listJobStatusHistory, listParts, getPrivateFileUrl, saveJobStatus, updateJob } from './lib/data';

const pretty = s => String(s || 'draft').replaceAll('_',' ');
export default function JobDetailPage({ jobId, onBack }) {
  const [job,setJob]=useState(null),[photos,setPhotos]=useState([]),[history,setHistory]=useState([]),[parts,setParts]=useState([]),[catalogue,setCatalogue]=useState([]),[urls,setUrls]=useState({}),[loading,setLoading]=useState(true),[error,setError]=useState(''),[saving,setSaving]=useState(false),[addingPart,setAddingPart]=useState(false),[partForm,setPartForm]=useState({part_id:'',description:'',quantity:'1',unit_cost:'',status:'used'}),[editing,setEditing]=useState(false),[form,setForm]=useState({problem:'',work_carried_out:'',labour_hours:'',travel:''});
  const load=async()=>{setLoading(true);setError('');try{const[j,p,h,partsData,cat]=await Promise.all([getJob(jobId),listJobPhotos(jobId),listJobStatusHistory(jobId),listJobParts(jobId),listParts()]);setJob(j);setForm({problem:j.problem||'',work_carried_out:j.work_carried_out||'',labour_hours:j.labour_hours??'',travel:j.travel??''});setPhotos(p);setHistory(h);setParts(partsData);setCatalogue(cat);const entries=await Promise.all(p.map(async x=>{try{return [x.id,await getPrivateFileUrl(x.storage_path)]}catch{return [x.id,'']}}));const signatureUrl=job.customer_signature_path?await getPrivateFileUrl(job.customer_signature_path).catch(()=> ''):'';setUrls({...Object.fromEntries(entries),signature:signatureUrl});}catch(e){setError(e.message||'Could not load job.')}finally{setLoading(false)}};
  useEffect(()=>{load()},[jobId]);
  if(loading)return <div className="loading-bar"><Loader2 className="spin" size={18}/> Loading job…</div>;
  if(error&&!job)return <div className="error-box">{error}<button className="text-btn" onClick={load}>Retry</button></div>;
  if(!job)return null;
  const status=pretty(job.status);
  const addPart=async()=>{if(!partForm.description.trim()){setError('Part description is required.');return}if(!Number.isFinite(Number(partForm.quantity))||Number(partForm.quantity)<=0){setError('Part quantity must be a valid number greater than zero.');return}if(partForm.unit_cost!==''&&(!Number.isFinite(Number(partForm.unit_cost))||Number(partForm.unit_cost)<=0)){setError('Part unit cost must be a valid number greater than zero.');return}setSaving(true);setError('');try{const selected=catalogue.find(p=>p.id===partForm.part_id);await createJobPart({job_id:job.id,part_id:partForm.part_id||null,part_number:selected?.part_number||null,description:partForm.description.trim(),quantity:Number(partForm.quantity),unit_cost:partForm.unit_cost===''?null:Number(partForm.unit_cost),status:partForm.status});setAddingPart(false);setPartForm({part_id:'',description:'',quantity:'1',unit_cost:'',status:'used'});await load()}catch(e){setError(e.message||'Could not add part.')}finally{setSaving(false)}};const saveEdits=async()=>{const numericFields=[['Labour hours',form.labour_hours],['Travel',form.travel]];const invalid=numericFields.find(([label,value])=>value!==''&&(!Number.isFinite(Number(value))||Number(value)<0));if(invalid){setError(`${invalid[0]} must be a valid non-negative number.`);return}setSaving(true);setError('');try{await updateJob(job.id,{problem:form.problem.trim()||null,work_carried_out:form.work_carried_out.trim()||null,labour_hours:form.labour_hours===''?null:Number(form.labour_hours),travel:form.travel===''?null:Number(form.travel)});setEditing(false);await load()}catch(e){setError(e.message||'Could not save job changes.')}finally{setSaving(false)}};const changeStatus=async(nextStatus,note)=>{if(nextStatus===job.status)return;setSaving(true);setError('');try{await saveJobStatus(job.id,job.status,nextStatus,note);await load()}catch(e){setError(e.message||'Could not update job status.')}finally{setSaving(false)}};const complete=async()=>{const unresolved=parts.filter(p=>['required','ordered'].includes(String(p.status).toLowerCase()));if(unresolved.length){setError(`${unresolved.length} part${unresolved.length===1?'':'s'} still ${unresolved.length===1?'requires':'require'} action before the jobsheet can be completed.`);return}await changeStatus('completed','Job completed by engineer.');};
  return <div className="detail-page">
    <div className="page-title"><div className="title-with-back"><button className="icon-btn" onClick={onBack}><ArrowLeft size={21}/></button><div><p className="eyebrow">JOB {job.job_number}</p><h1>{job.problem||'Jobsheet'}</h1><p className="muted">{job.customers?.name||'No customer'} · {job.sites?.name||'No site'}</p></div></div><span className={`status ${status.replaceAll(' ','-')}`}>{status}</span></div>
    {error&&<div className="error-box" role="alert">{error}</div>}
    <section className="detail-card"><h2>Job details</h2><div className="detail-grid"><div><span>Forklift</span><strong>Plant {job.forklifts?.plant_number||'—'} · {[job.forklifts?.make,job.forklifts?.model].filter(Boolean).join(' ')||'—'}</strong></div><div><span>Serial</span><strong>{job.forklifts?.serial_number||'—'}</strong></div><div><span>Engineer</span><strong>{job.engineer_name||'—'}</strong></div><div><span>Date</span><strong>{job.job_date||'—'}</strong></div><div><span>Labour hours</span><strong>{job.labour_hours??'—'}</strong></div><div><span>Travel</span><strong>{job.travel??'—'}</strong></div></div></section>
    <section className="detail-card"><div className="section-head"><h2>Job details</h2><button className="secondary" onClick={()=>setEditing(v=>!v)} disabled={saving}>{editing?<><Edit3 size={17}/> Cancel</>:<><Edit3 size={17}/> Edit</>}</button></div>{editing?<div className="form-grid"><label className="full">Problem / fault<textarea value={form.problem} onChange={e=>setForm({...form,problem:e.target.value})}/></label><label className="full">Work carried out<textarea value={form.work_carried_out} onChange={e=>setForm({...form,work_carried_out:e.target.value})}/></label><label>Labour hours<input type="number" min="0" step="0.01" inputMode="decimal" value={form.labour_hours} onChange={e=>setForm({...form,labour_hours:e.target.value})}/></label><label>Travel<input type="number" min="0" step="0.01" inputMode="decimal" value={form.travel} onChange={e=>setForm({...form,travel:e.target.value})}/></label><button className="primary wide" disabled={saving} onClick={saveEdits}><Save size={18}/>{saving?'Saving…':'Save changes'}</button></div>:<><div className="detail-grid"><div><span>Labour hours</span><strong>{job.labour_hours??'—'}</strong></div><div><span>Travel</span><strong>{job.travel??'—'}</strong></div></div><h3>Problem / fault</h3><p className="long-copy">{job.problem||'No problem recorded.'}</p><h3>Work carried out</h3><p className="long-copy">{job.work_carried_out||'No work recorded yet.'}</p></>}</section>
    <section className="detail-card"><div className="section-head"><h2><Wrench size={19}/> Parts used / required</h2><button className="secondary" onClick={()=>setAddingPart(v=>!v)} disabled={saving}>{addingPart?'Cancel':'+ Add part'}</button></div>{addingPart&&<div className="form-grid"><label className="full">Catalogue part<select value={partForm.part_id} onChange={e=>{const p=catalogue.find(x=>x.id===e.target.value);setPartForm({...partForm,part_id:e.target.value,description:p?.description||partForm.description,unit_cost:p?.default_unit_cost??partForm.unit_cost})}}><option value="">Manual part / description</option>{catalogue.map(p=><option key={p.id} value={p.id}>{p.part_number||'No number'} · {p.description}</option>)}</select></label><label className="full">Description<input value={partForm.description} onChange={e=>setPartForm({...partForm,description:e.target.value})}/></label><label>Quantity<input type="number" min="0.01" step="0.01" value={partForm.quantity} onChange={e=>setPartForm({...partForm,quantity:e.target.value})}/></label><label>Unit cost £<input inputMode="decimal" value={partForm.unit_cost} onChange={e=>setPartForm({...partForm,unit_cost:e.target.value})}/></label><label>Status<select value={partForm.status} onChange={e=>setPartForm({...partForm,status:e.target.value})}><option value="used">Used</option><option value="required">Required</option><option value="ordered">Ordered</option><option value="received">Received</option></select></label><button className="primary wide" disabled={saving} onClick={addPart}><Save size={18}/>{saving?'Saving…':'Add part to job'}</button></div>}{parts.length?<div className="job-list">{parts.map(p=><div className="job-card" key={p.id}><div className="job-top"><span className="job-id">{p.part_number||'PART'}</span><span className="status awaiting-parts">{p.status}</span></div><div className="card-title">{p.description}</div><div className="meta"><span>Qty {p.quantity}</span><span>{p.unit_cost==null?'Cost not set':'£'+Number(p.unit_cost).toFixed(2)+' each'}</span><span>Total {p.unit_cost==null?'—':'£'+(Number(p.unit_cost)*Number(p.quantity)).toFixed(2)}</span></div></div>)}</div>:<p className="muted">No parts linked to this job yet.</p>}</section>    {job.source_document_path&&<section className="detail-card"><h2><FileImage size={19}/> Original jobsheet</h2><p className="muted">The original source remains attached as evidence.</p><button className="secondary" onClick={async()=>{try{const u=await getPrivateFileUrl(job.source_document_path);window.open(u,'_blank','noopener,noreferrer')}catch(e){setError(e.message||'Could not open original.')}}}><Download size={17}/> Open original</button></section>}
    <section className="detail-card"><div className="section-head"><h2>Evidence photos</h2><span className="hint">{photos.length} attached</span></div>{photos.length?<div className="photo-grid">{photos.map(p=><a key={p.id} href={urls[p.id]} target="_blank" rel="noreferrer"><img src={urls[p.id]} alt={p.caption||p.tag||'Job evidence'}/><span>{p.tag||'evidence'}</span></a>)}</div>:<p className="muted">No evidence photos attached.</p>}</section>
    <section className="detail-card"><h2><PenLine size={19}/> Customer signature</h2>{job.customer_signature_path?<div className="signature-result"><img src={urls.signature||''} alt="Customer signature"/><button className="secondary" onClick={async()=>{try{const u=await getPrivateFileUrl(job.customer_signature_path);setUrls(x=>({...x,signature:u}))}catch(e){setError(e.message||'Could not open signature.')}}}><Download size={17}/> Open signature</button></div>:<p className="muted">No customer signature attached yet.</p>}</section>
    <section className="detail-card"><h2><History size={19}/> Status history</h2>{history.length?<div className="timeline">{history.map(h=><div key={h.id}><Clock3 size={15}/><div><strong>{pretty(h.new_status)}</strong><span>{new Date(h.changed_at).toLocaleString('en-GB')}</span>{h.note&&<p>{h.note}</p>}</div></div>)}</div>:<p className="muted">No status changes recorded.</p>}</section>
    {!['completed','cancelled'].includes(String(job.status).toLowerCase())&&<><section className="detail-card"><h2>Update status</h2><div className="filter-row"><button className="secondary" disabled={saving||job.status==='in_progress'} onClick={()=>changeStatus('in_progress','Job started by engineer.')}>In progress</button><button className="secondary" disabled={saving||job.status==='awaiting_parts'} onClick={()=>changeStatus('awaiting_parts','Parts required before completion.')}>Awaiting parts</button></div></section><button className="primary wide" disabled={saving} onClick={complete}>{saving?<Loader2 className="spin" size={18}/>:<CheckCircle2 size={18}/>} Complete jobsheet</button></>}
    <div className="privacy-note"><Wrench size={15}/> Completion records a status-history event so changes remain auditable.</div>
  </div>;
}
