import React, { useEffect, useRef, useState } from 'react';
import { ArrowLeft, Camera, Check, FileImage, Loader2, Mic, PenLine, Sparkles, X } from 'lucide-react';
import { createJob, attachJobSource, listCustomers, listForklifts, listSites } from './lib/data';
import { supabase } from './lib/supabase';

export default function NewJobPage({ onBack, onSaved }) {
  const [mode,setMode]=useState(null),[customers,setCustomers]=useState([]),[forklifts,setForklifts]=useState([]),[sites,setSites]=useState([]),[customerId,setCustomerId]=useState(''),[siteId,setSiteId]=useState(''),[forkliftId,setForkliftId]=useState(''),[problem,setProblem]=useState(''),[work,setWork]=useState(''),[hours,setHours]=useState(''),[travel,setTravel]=useState(''),[recording,setRecording]=useState(false),[transcript,setTranscript]=useState(''),[voiceError,setVoiceError]=useState(''),[file,setFile]=useState(null),[saving,setSaving]=useState(false),[error,setError]=useState('');
  const inputRef=useRef(null),recognitionRef=useRef(null);
  useEffect(()=>{if(!supabase)return;Promise.all([listCustomers(),listForklifts()]).then(([c,f])=>{setCustomers(c);setForklifts(f)}).catch(e=>setError(e.message||'Could not load job options.'));return()=>recognitionRef.current?.stop()},[]);
  useEffect(()=>{if(!customerId){setSites([]);setSiteId('');return}listSites(customerId).then(setSites).catch(e=>setError(e.message||'Could not load sites.'))},[customerId]);
  const chooseScan=()=>{setMode('scan');setTimeout(()=>inputRef.current?.click(),0)};
  const onFile=e=>{const f=e.target.files?.[0];if(f){setFile(f);setMode('review')}};
  const save=async(extra={})=>{if(!supabase){setError('Cloud database is not configured.');return}if(!customerId||!forkliftId){setError('Select the customer and forklift before saving.');return}setSaving(true);setError('');try{const j=await createJob({customer_id:customerId,site_id:siteId||null,forklift_id:forkliftId,job_date:new Date().toISOString().slice(0,10),problem:extra.problem??problem,work_carried_out:work||null,labour_hours:hours?Number(hours):null,travel:travel?Number(travel):null,status:'draft',engineer_name:null});if(file)await attachJobSource(j.id,file);onSaved?.(j)}catch(e){setError(e.message||'Could not save jobsheet.')}finally{setSaving(false)}};
  const toggleVoice=()=>{setVoiceError('');const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){setVoiceError('Voice recognition is not available here. Try Chrome on Android.');return}if(recording){recognitionRef.current?.stop();setRecording(false);return}const r=new SR();r.lang='en-GB';r.continuous=true;r.interimResults=true;r.onresult=e=>{let finalText='';for(let i=e.resultIndex;i<e.results.length;i++)if(e.results[i].isFinal)finalText+=e.results[i][0].transcript+' ';if(finalText)setTranscript(t=>`${t} ${finalText}`.trim())};r.onerror=e=>{setRecording(false);setVoiceError(`Voice input stopped: ${e.error}.`)};r.onend=()=>setRecording(false);recognitionRef.current=r;r.start();setRecording(true)};
  const reset=()=>{recognitionRef.current?.stop();setRecording(false);setMode(null);setFile(null);setTranscript('');setProblem('');setWork('');setError('')};
  return <div className="new-job-page"><div className="page-title"><div className="title-with-back"><button className="icon-btn" onClick={onBack}><ArrowLeft size={21}/></button><div><h1>New jobsheet</h1><p className="muted">Choose the quickest way to record the job.</p></div></div><span className="mini-help"><Sparkles size={14}/> Review before completion</span></div>{error&&<div className="error-box" role="alert">{error}</div>}
  {!mode&&<div className="capture-grid"><button className="capture-card featured" onClick={chooseScan}><div className="capture-icon"><Camera/></div><strong>Scan paper jobsheet</strong><span>Keep the original photograph attached to the job.</span><b>Take photo / choose image →</b></button><button className="capture-card" onClick={()=>setMode('voice')}><div className="capture-icon"><Mic/></div><strong>Voice jobsheet</strong><span>Speak naturally, then review the transcript.</span><b>Start voice entry →</b></button><button className="capture-card" onClick={()=>setMode('type')}><div className="capture-icon"><PenLine/></div><strong>Type jobsheet</strong><span>Enter exact details yourself.</span><b>Open form →</b></button></div>}
  {mode==='scan'&&<div className="capture-state"><div className="large-icon"><Camera/></div><h2>Scan your paper sheet</h2><p>Take a clear photo showing the whole signed jobsheet. The original will be stored; no fake OCR result is generated.</p><button className="primary wide" onClick={()=>inputRef.current?.click()}><Camera size={18}/> Choose photo</button><input ref={inputRef} type="file" accept="image/*" capture="environment" hidden onChange={onFile}/><button className="secondary wide" onClick={reset}>Cancel</button></div>}
  {mode==='review'&&<div className="review-card"><div className="review-head"><div><span className="eyebrow">SOURCE DOCUMENT</span><h2>{file?.name}</h2></div><button className="icon-btn" onClick={reset}><X/></button></div><div className="ai-banner"><FileImage size={18}/><div><strong>Original ready to attach</strong><p>The paper image will be preserved. Enter the key fields below; handwriting extraction can be added without replacing the source.</p></div></div><JobFields {...{customers,sites,forklifts,customerId,setCustomerId,siteId,setSiteId,forkliftId,setForkliftId,problem,setProblem,work,setWork,hours,setHours,travel,setTravel}}/><button className="primary wide" disabled={saving} onClick={()=>save()}>{saving?<Loader2 className="spin" size={18}/>:<Check size={18}/>} Save jobsheet with original</button><button className="secondary wide" onClick={()=>setMode('scan')}>Retake</button></div>}
  {mode==='voice'&&<div className="capture-state"><div className={`large-icon mic ${recording?'recording':''}`}><Mic/></div><h2>{recording?'Listening…':'Talk through the job'}</h2><p>Say the customer, truck, fault, work, hours and travel naturally.</p><button className="primary wide" onClick={toggleVoice}>{recording?'Stop recording':'Start voice-to-text'}</button>{voiceError&&<div className="example">{voiceError}</div>}{transcript&&<div className="transcript"><strong>Transcript</strong><textarea value={transcript} onChange={e=>setTranscript(e.target.value)}/></div>}{transcript&&<JobFields {...{customers,sites,forklifts,customerId,setCustomerId,siteId,setSiteId,forkliftId,setForkliftId,problem,setProblem,work,setWork,hours,setHours,travel,setTravel}}/>}{transcript&&<button className="primary wide" disabled={saving} onClick={()=>save({problem:problem||transcript})}>{saving?<Loader2 className="spin" size={18}/>:<Check size={18}/>} Save voice job</button>}<button className="secondary wide" onClick={reset}>Cancel</button></div>}
  {mode==='type'&&<div className="form-card"><div className="form-head"><div><h2>Digital jobsheet</h2><p className="muted">Save a real draft to the shared KNT database.</p></div></div><JobFields {...{customers,sites,forklifts,customerId,setCustomerId,siteId,setSiteId,forkliftId,setForkliftId,problem,setProblem,work,setWork,hours,setHours,travel,setTravel}}/><button className="primary wide" disabled={saving} onClick={()=>save()}>{saving?<Loader2 className="spin" size={18}/>:<Check size={18}/>} Save draft</button><button className="secondary wide" onClick={reset}>Cancel</button></div>}
  <p className="privacy-note"><FileImage size={15}/> Source photos stay attached to the job record; extracted or dictated text is editable and never silently replaces evidence.</p></div>;
}
function JobFields(p){const{customers,sites,forklifts,customerId,setCustomerId,siteId,setSiteId,forkliftId,setForkliftId,problem,setProblem,work,setWork,hours,setHours,travel,setTravel}=p;const available=customerId?forklifts.filter(f=>f.customer_id===customerId):forklifts;return <><label>Customer<select value={customerId} onChange={e=>setCustomerId(e.target.value)}><option value="">Select customer…</option>{customers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Site<select value={siteId} onChange={e=>setSiteId(e.target.value)} disabled={!customerId}><option value="">Select site…</option>{sites.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Forklift / plant<select value={forkliftId} onChange={e=>setForkliftId(e.target.value)}><option value="">Select forklift…</option>{available.map(f=><option key={f.id} value={f.id}>Plant {f.plant_number} · {f.make} {f.model} · {f.serial_number}</option>)}</select></label><label>Problem / fault<textarea value={problem} onChange={e=>setProblem(e.target.value)} placeholder="What did the customer report?"/></label><label>Work carried out<textarea value={work} onChange={e=>setWork(e.target.value)} placeholder="What did you find and do?"/></label><div className="two-col"><label>Labour hours<input inputMode="decimal" value={hours} onChange={e=>setHours(e.target.value)} placeholder="0"/></label><label>Travel<input inputMode="decimal" value={travel} onChange={e=>setTravel(e.target.value)} placeholder="0"/></label></div></>}
