import React,{useEffect,useState}from'react';
import{Package,Plus,Truck,X,ClipboardList}from'lucide-react';
import{createSupplier,createSupplierOrder,createSupplierOrderLine,listJobs,listJobParts,listParts,listSupplierOrderLines,listSupplierOrders,listSuppliers,updateJobPart,updateSupplierOrder}from'./lib/data';
import{supabase}from'./lib/supabase';

export default function PartsSuppliersPage(){
 const[suppliers,setSuppliers]=useState([]),[parts,setParts]=useState([]),[orders,setOrders]=useState([]),[jobs,setJobs]=useState([]),[tab,setTab]=useState('suppliers');
 const[open,setOpen]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState('');
 const[form,setForm]=useState({name:'',account_number:'',phone:'',email:'',notes:''});
 const[order,setOrder]=useState({supplier_id:'',order_number:'',job_id:'',part_id:'',description:'',quantity:'1',unit_cost:'',status:'ordered'});
 const load=async()=>{try{const[a,b,c,d]=await Promise.all([listSuppliers(),listParts(),listSupplierOrders(),listJobs()]);setSuppliers(a);setParts(b);setOrders(c);setJobs(d)}catch(e){setError(e.message)}};
 useEffect(()=>{if(supabase)load()},[]);
 const saveSupplier=async()=>{if(!form.name.trim())return;setSaving(true);try{await createSupplier(form);setOpen(false);setForm({name:'',account_number:'',phone:'',email:'',notes:''});await load()}catch(e){setError(e.message)}finally{setSaving(false)}};
 const selectedPart=parts.find(p=>p.id===order.part_id);
 const saveOrder=async()=>{if(!order.supplier_id||!order.order_number.trim()||!order.description.trim())return;
  setSaving(true);setError('');
  try{const o=await createSupplierOrder({supplier_id:order.supplier_id,order_number:order.order_number.trim(),order_date:new Date().toISOString().slice(0,10),status:order.status,notes:null});
   await createSupplierOrderLine({supplier_order_id:o.id,part_id:order.part_id||null,part_number:selectedPart?.part_number||null,description:order.description.trim(),quantity:Number(order.quantity)||1,unit_cost:order.unit_cost===''?(selectedPart?.default_unit_cost??null):Number(order.unit_cost),job_id:order.job_id||null});
   if(order.job_id){const jp=await listJobParts(order.job_id);const match=jp.find(x=>(order.part_id&&x.part_id===order.part_id)||(!order.part_id&&x.description?.trim()===order.description.trim()));if(match)await updateJobPart(match.id,{status:order.status==='received'?'received':'ordered',supplier:suppliers.find(s=>s.id===order.supplier_id)?.name||null,supplier_order_number:order.order_number.trim()})}
   setOpen(false);setOrder({supplier_id:'',order_number:'',job_id:'',part_id:'',description:'',quantity:'1',unit_cost:'',status:'ordered'});await load()
  }catch(e){setError(e.message)}finally{setSaving(false)}
 };
 const receiveOrder=async(id)=>{try{await updateSupplierOrder(id,{status:'received'});await load()}catch(e){setError(e.message)}};
 if(!supabase)return <div className="empty-state"><Package size={30}/><strong>Cloud setup required</strong></div>;
 return <><div className="page-title"><div><h1>Parts & suppliers</h1><p className="muted">Manage parts, suppliers and orders for jobs waiting on parts.</p></div>{tab==='suppliers'?<button className="primary"onClick={()=>setOpen(true)}><Plus size={18}/> Supplier</button>:tab==='orders'?<button className="primary"onClick={()=>setOpen(true)}><Plus size={18}/> Order</button>:null}</div>
 {error&&<div className="error-box">{error}</div>}
 <div className="filter-row">
  <button className={`chip ${tab==='suppliers'?'active':''}`}onClick={()=>setTab('suppliers')}>Suppliers ({suppliers.length})</button>
  <button className={`chip ${tab==='parts'?'active':''}`}onClick={()=>setTab('parts')}>Parts ({parts.length})</button>
  <button className={`chip ${tab==='orders'?'active':''}`}onClick={()=>setTab('orders')}>Orders ({orders.length})</button>
 </div>
 {tab==='suppliers'&&<div className="job-list">{suppliers.map(s=><div className="job-card"key={s.id}><div className="card-title">{s.name}</div><div className="muted">{s.account_number||'No account number'}{s.phone?` · ${s.phone}`:''}</div><div className="meta"><span>{s.email||'No email'}</span></div></div>)}{!suppliers.length&&<div className="empty-state"><Truck size={30}/><strong>No suppliers yet</strong></div>}</div>}
 {tab==='parts'&&<div className="job-list">{parts.map(p=><div className="job-card"key={p.id}><div className="card-title">{p.description}</div><div className="muted">{p.part_number||'No part number'}</div><div className="meta"><span>Cost £{Number(p.default_unit_cost||0).toFixed(2)}</span><span>Sell £{Number(p.default_sell_price||0).toFixed(2)}</span></div></div>)}{!parts.length&&<div className="empty-state"><Package size={30}/><strong>No parts yet</strong></div>}</div>}
 {tab==='orders'&&<div className="job-list">{orders.map(o=><OrderCard key={o.id} order={o} onReceive={receiveOrder}/>) }{!orders.length&&<div className="empty-state"><ClipboardList size={30}/><strong>No supplier orders yet</strong><span>Create an order when a jobsheet needs parts.</span></div>}</div>}
 {open&&<div className="modal-backdrop"><div className="modal"><div className="modal-head"><strong>{tab==='orders'?'New supplier order':'New supplier'}</strong><button className="icon-btn"onClick={()=>setOpen(false)}><X/></button></div>
 {tab==='suppliers'?<><label>Name<input value={form.name}onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Account number<input value={form.account_number}onChange={e=>setForm({...form,account_number:e.target.value})}/></label><label>Phone<input value={form.phone}onChange={e=>setForm({...form,phone:e.target.value})}/></label><label>Email<input type="email"value={form.email}onChange={e=>setForm({...form,email:e.target.value})}/></label><button className="primary wide"disabled={saving}onClick={saveSupplier}>{saving?'Saving…':'Save supplier'}</button></>:<><label>Supplier<select value={order.supplier_id}onChange={e=>setOrder({...order,supplier_id:e.target.value})}><option value="">Select supplier…</option>{suppliers.map(s=><option key={s.id}value={s.id}>{s.name}</option>)}</select></label><label>Order number<input value={order.order_number}onChange={e=>setOrder({...order,order_number:e.target.value})}placeholder="Supplier PO / order number"/></label>
<label>Job<select value={order.job_id}onChange={async e=>{const id=e.target.value;setOrder({...order,job_id:id});if(id){try{const js=await listJobParts(id);const required=js.find(x=>x.status==='required');if(required)setOrder(x=>({...x,job_id:id,part_id:required.part_id||'',description:required.description,quantity:String(required.quantity||1),unit_cost:required.unit_cost??''}))}catch(err){setError(err.message)}}}}><option value="">Optional linked job…</option>{jobs.map(j=><option key={j.id}value={j.id}>Job {j.job_number} · {j.problem||'No problem'}</option>)}</select></label><label>Part<select value={order.part_id}onChange={e=>{const id=e.target.value,p=parts.find(x=>x.id===id);setOrder({...order,part_id:id,description:p?.description||order.description,unit_cost:p?.default_unit_cost??order.unit_cost})}}><option value="">Manual part…</option>{parts.map(p=><option key={p.id}value={p.id}>{p.part_number||'No number'} · {p.description}</option>)}</select></label><label>Description<input value={order.description}onChange={e=>setOrder({...order,description:e.target.value})}/></label>
<div className="two-col"><label>Quantity<input inputMode="decimal"value={order.quantity}onChange={e=>setOrder({...order,quantity:e.target.value})}/></label><label>Unit cost £<input inputMode="decimal"value={order.unit_cost}onChange={e=>setOrder({...order,unit_cost:e.target.value})}/></label></div><label>Status<select value={order.status}onChange={e=>setOrder({...order,status:e.target.value})}><option value="ordered">Ordered</option><option value="received">Received</option></select></label><button className="primary wide"disabled={saving||!order.supplier_id||!order.order_number.trim()||!order.description.trim()}onClick={saveOrder}>{saving?'Saving…':'Create supplier order'}</button></>}</div></div>}</>}
function OrderCard({order,onReceive}){const[lines,setLines]=useState([]);useEffect(()=>{listSupplierOrderLines(order.id).then(setLines).catch(()=>{})},[order.id]);return <div className="job-card"><div className="job-top"><span className="job-id">PO {order.order_number}</span><span className={`status ${order.status==='received'?'complete':'awaiting-parts'}`}>{order.status}</span></div><div className="card-title">{order.suppliers?.name||'Supplier'}</div>{lines.map(l=><div className="muted"key={l.id}>{l.description} × {Number(l.quantity||1)}{l.job_id?' · linked to job':''}</div>)}<div className="meta"><span>{order.order_date||'No date'}</span>{order.status!=='received'&&<button className="chip active"onClick={()=>onReceive(order.id)}>Mark received</button>}</div></div>}
