import React from "react";
export default function PublicSite(){
 return <div className="public-site"><script type="application/ld+json">{JSON.stringify({"@context":"https://schema.org","@type":"LocalBusiness","name":"KNT Hire & Sales Ltd","telephone":"+44 1377 200523","url":"/","address":{"@type":"PostalAddress","streetAddress":"2 Wood Lane","addressLocality":"Driffield","postalCode":"YO25 6DU","addressCountry":"GB"},"areaServed":"East Yorkshire"})}</script>
  <a className="skip-link" href="#main-content">Skip to content</a><header className="site-header"><a href="#top"><img src="/knt-logo-header.jpg" alt="KNT Hire & Sales Ltd"/></a><nav aria-label="Main navigation"><a href="#stock">Forklifts for Sale</a><a href="#services">Services</a><a href="#about">About</a><a href="#contact">Contact</a></nav><a className="header-call" href="tel:01377200523">Call KNT</a></header>
  <main id="main-content" className="public-main">
   <section className="hero"><div className="hero-copy"><p className="eyebrow">DRIFFIELD · EAST YORKSHIRE</p><h1>Quality forklifts<br/><span>Hire · Sales · Servicing</span></h1><p>K&T Hire & Sales Ltd supplies quality used forklifts, flexible hire options and practical servicing support across East Yorkshire and beyond.</p><div className="actions"><a className="primary" href="#stock">View forklifts for sale →</a><a className="secondary" href="#contact">Enquire now →</a></div></div><div className="hero-photo"><img src="/stock/knt-fleet.jpg" alt="K&T Hire and Sales forklift fleet"/></div></section>
   <section className="service-strip" id="services" aria-label="K&T services"><a href="#contact"><b>HIRE</b><span>Short & long-term hire</span></a><a href="#stock"><b>SALES</b><span>Quality used forklifts</span></a><a href="#contact"><b>SERVICING</b><span>Repairs & maintenance</span></a><a href="#contact"><b>PARTS</b><span>Advice & support</span></a></section>
   <section className="section" id="stock"><p className="eyebrow">CURRENT STOCK</p><h2>Forklifts <em>for sale</em></h2><div className="stock-grid"><Stock name="Daewoo D15S" image="/stock/knt-fleet.jpg" meta="Used forklift · diesel"/><Stock name="Mitsubishi Grendia 20" image="/stock/knt-fleet.jpg" meta="Used forklift · LPG"/><Stock name="Mitsubishi FG25N" image="/stock/knt-fleet.jpg" meta="Used forklift · LPG"/></div></section>
   <section className="section services-section"><div><p className="eyebrow">OUR SERVICES</p><h2>Supporting your business</h2><p>From single forklift hire to fleet support, K&T Hire & Sales Ltd provides a practical, professional service.</p><a className="secondary dark-button" href="#contact">Find out more →</a></div><div className="service-cards"><article><img src="/stock/knt-fleet.jpg" alt="" /><b>Forklift hire</b><span>Short & long term options.</span></article><article><img src="/stock/knt-fleet.jpg" alt="" /><b>Servicing & repairs</b><span>Keep your fleet running.</span></article><article><img src="/stock/knt-fleet.jpg" alt="" /><b>Parts & attachments</b><span>Advice and support.</span></article><article><img src="/stock/knt-fleet.jpg" alt="" /><b>Sales</b><span>Quality used forklifts.</span></article></div></section><section className="section dark" id="about"><p className="eyebrow">ABOUT KNT</p><h2>A local forklift business with a practical approach.</h2><p>KNT Hire & Sales Ltd is based in Driffield, East Yorkshire. Machine specifications, hours and prices will only be published after KNT confirms them.</p></section>
   <section className="section contact" id="contact"><p className="eyebrow">GET IN TOUCH</p><h2>Need a forklift?</h2><p>Sales, hire, servicing and repair enquiries.</p><a className="primary" href="tel:01377200523">01377 200523</a><a className="phone" href="tel:07702813510">07702 813510</a><a className="secondary" href="https://wa.me/447702813510" target="_blank" rel="noreferrer">Message KNT on WhatsApp</a><p>2 Wood Lane, Driffield, YO25 6DU</p></section>
  </main><footer><img src="/knt-logo-header.jpg" alt="KNT Hire & Sales Ltd" onError={e=>{e.currentTarget.onerror=null;e.currentTarget.src="/knt-logo.svg"}}/><a href="/app">KNT App</a></footer>
 </div>;
}
function Stock({name,image,meta}){return <article className="stock-card"><div className="machine-photo"><img src={image} alt={`${name} forklift`} loading="lazy"/></div><small>{meta.toUpperCase()}</small><h3>{name}</h3><p>Real KNT stock photography. Full specification, hours and price to be confirmed by KNT.</p><a href="#contact">Enquire about this machine →</a></article>}
