import React from "react";
export default function PublicSite(){
 return <div className="public-site"><script type="application/ld+json">{JSON.stringify({"@context":"https://schema.org","@type":"LocalBusiness","name":"KNT Hire & Sales Ltd","telephone":"+44 1377 200523","url":"/","address":{"@type":"PostalAddress","streetAddress":"2 Wood Lane","addressLocality":"Driffield","postalCode":"YO25 6DU","addressCountry":"GB"},"areaServed":"East Yorkshire"})}</script>
  <a className="skip-link" href="#main-content">Skip to content</a><header className="site-header"><a href="#top"><img src="/knt-logo.webp?v=2" alt="KNT Hire & Sales Ltd" onError={e=>{e.currentTarget.onerror=null;e.currentTarget.src="/knt-logo.svg"}}/></a><nav aria-label="Main navigation"><a href="#stock">Forklifts for Sale</a><a href="#services">Services</a><a href="#about">About</a><a href="#contact">Contact</a></nav><a className="header-call" href="tel:01377200523">Call KNT</a></header>
  <main id="main-content" className="public-main">
   <section className="hero"><div><p className="eyebrow">DRIFFIELD · EAST YORKSHIRE</p><h1>Forklift trucks.<br/><span>Hire. Sales. Support.</span></h1><p>KNT Hire & Sales provides forklift hire, used forklift sales and practical support for businesses across East Yorkshire and beyond.</p><div className="actions"><a className="primary" href="#stock">View forklifts for sale</a><a className="secondary" href="#contact">Get in touch</a><a className="phone" href="tel:01377200523" aria-label="Call KNT Hire and Sales on 01377 200523">Call 01377 200523</a><a className="phone" href="https://wa.me/447702813510" target="_blank" rel="noreferrer">WhatsApp enquiry</a></div></div><div className="hero-art"><div className="forklift">KNT</div><strong>FORKLIFT TRUCKS</strong></div></section>
   <section className="service-strip" id="services" aria-label="KNT services"><a href="#contact"><b>HIRE</b><span>Short & long-term enquiries</span></a><a href="#stock"><b>SALES</b><span>Used forklifts currently available</span></a><a href="#contact"><b>SERVICING</b><span>Maintenance & repairs</span></a><a href="#contact"><b>SUPPORT</b><span>LOLER & compliance workflows</span></a></section>
   <section className="section" id="stock"><p className="eyebrow">CURRENT STOCK</p><h2>Forklifts <em>for sale</em></h2><div className="stock-grid"><Stock name="Daewoo D15S" image="/stock/daewoo-d15s.jpg" meta="Used forklift · diesel" detail="Real KNT stock photography available."/><Stock name="Mitsubishi Grendia 20" image="/stock/mitsubishi-grendia-20.jpg" meta="Used forklift · LPG" detail="Real KNT stock photography available."/><Stock name="Mitsubishi FG25N" image="/stock/mitsubishi-fg25n.jpg" meta="Used forklift · LPG" detail="Real KNT stock photography available."/></div></section>
   <section className="section dark" id="about"><p className="eyebrow">ABOUT KNT</p><h2>A local forklift business with a practical approach.</h2><p>KNT Hire & Sales Ltd is based in Driffield, East Yorkshire. Machine specifications, hours and prices will only be published after KNT confirms them.</p></section>
   <section className="section contact" id="contact"><p className="eyebrow">GET IN TOUCH</p><h2>Need a forklift?</h2><p>Sales, hire, servicing and repair enquiries.</p><a className="primary" href="tel:01377200523">01377 200523</a><a className="phone" href="tel:07702813510">07702 813510</a><a className="secondary" href="https://wa.me/447702813510" target="_blank" rel="noreferrer">Message KNT on WhatsApp</a><p>2 Wood Lane, Driffield, YO25 6DU</p></section>
  </main><footer><img src="/knt-logo.webp?v=2" alt="KNT Hire & Sales Ltd" onError={e=>{e.currentTarget.onerror=null;e.currentTarget.src="/knt-logo.svg"}}/><a href="/app">KNT App</a></footer>
 </div>;
}
function Stock({name,image,meta,detail}){return <article className="stock-card"><div className="machine-photo"><img src={image} alt={`${name} forklift`} loading="lazy"/></div><small>{meta.toUpperCase()}</small><h3>{name}</h3><p>{detail}</p><a href="#contact">Enquire about this machine →</a></article>}
