import React,{useEffect,useMemo,useState}from'react';
import{FileText,Plus,Save,Trash2}from'lucide-react';
import{createQuote,createQuoteLine,listCustomers,listQuotes,updateQuote}from'./lib/data';
import{supabase}from'./lib/supabase';

export default function QuotePage(){
 const[customers,setCustomers]=useState([]),[quotes,setQuotes]=useState([]),[customerId,setCustomerId]=useState(''),[notes,setNotes]=useState(''),[validUntil,setValidUntil]=useState(''),[vat,setVat]=useState('20'),[lines,setLines]=useState([{description:'',quantity:'1',unit_price:'',vat_rate:'20'}]),[saving,setSaving]=useState(false),[error,setError]=useState('');
 useEffect(()=>{if(!supabase)return;Promise.all([listCustomers(),listQuotes()]).then(([c,q])=>{setCustomers(c);setQuotes(q)}).catch(e=>setError(e.message))},[]);
 const subtotal=useMemo(()=>lines.reduce((s,l)=>s+(Number(l.quantity)||0)*(Number(l.unit_price)||0),0),[lines]);
 const lineVat=useMemo(()=>lines.reduce((s,l)=>s+(Number(l.quantity)||0)*(Number(l.unit_price)||0)*(Number(l.vat_rate||vat)||0)/100,0),[lines,vat]);
 const total=subtotal+lineVat;
 const setLine=(i,key,value)=>setLines(xs=>xs.map((x,n)=>n===i?{...x,[key]:value}:x));
 const addLine=()=>setLines(xs=>[...xs,{description:'',quantity:'1',unit_price:'',vat_rate:vat}]);
 const removeLine=i=>setLines(xs=>xs.length===1?xs:xs.filter((_,n)=>n!==i));
 const save=async()=>{if(!Number.isFinite(Number(vat))||Number(vat)<0){setError('Default VAT must be a valid non-negative number.');return}const invalid=lines.find(x=>!x.description.trim()||!Number.isFinite(Number(x.quantity))||Number(x.quantity)<=0||!Number.isFinite(Number(x.unit_price))||Number(x.unit_price)<0||!Number.isFinite(Number(x.vat_rate))||Number(x.vat_rate)<0);if(invalid){setError('Each quote line needs a description, quantity greater than zero, and valid non-negative price/VAT values.');return}const valid=lines.filter(x=>x.description.trim()&&(Number(x.quantity)||0)>0);if(!customerId){setError('Select a customer before saving the quote.');return}if(!valid.length){setError('Add at least one quote line.');return}setSaving(true);setError('');try{const q=await createQuote({customer_id:customerId,status:'draft',valid_until:validUntil||null,notes:notes.trim()||null,subtotal,vat:lineVat,total});for(const l of valid)await createQuoteLine({quote_id:q.id,description:l.description.trim(),quantity:Number(l.quantity)||1,unit_price:Number(l.unit_price)||0,vat_rate:Number(l.vat_rate||vat)||0});setQuotes([q,...quotes]);setLines([{description:'',quantity:'1',unit_price:'',vat_rate:vat}]);setNotes('');setValidUntil('');}catch(e){setError(e.message||'Could not save quote.')}finally{setSaving(false)}};
 if(!supabase)return <div className="empty-state"><FileText size={30}/><strong>Cloud setup required</strong><span>Connect Supabase to manage quotes.</span></div>;
 return <><div className="page-title"><div><h1>Quotes</h1><p className="muted">Prepare customer quotes that can flow directly into invoices.</p></div></div>{error&&<div className="error-box"role="alert">{error}</div>}<div className="form-card"><h2>New quote</h2><label>Customer<select value={customerId}onChange={e=>setCustomerId(e.target.value)}><option value="">Select customer…</option>{customers.map(c=><option key={c.id}value={c.id}>{c.name}</option>)}</select></label><div className="two-col"><label>Valid until<input type="date"value={validUntil}onChange={e=>setValidUntil(e.target.value)}/></label><label>Default VAT %<input type="number" min="0" step="0.01" inputMode="decimal"value={vat}onChange={e=>{setVat(e.target.value);setLines(xs=>xs.map(x=>({...x,vat_rate:e.target.value})))}}/></label></div><div className="detail-card"><div className="section-head"><h3>Quote lines</h3><button className="secondary"onClick={addLine}><Plus size={17}/> Add line</button></div>{lines.map((l,i)=><div className="quote-line"key={i}><input className="grow"placeholder="Description"value={l.description}onChange={e=>setLine(i,'description',e.target.value)}/><input type="number" min="0.01" step="0.01" aria-label="Quantity" placeholder="Qty" value={l.quantity}onChange={e=>setLine(i,'quantity',e.target.value)}/><input type="number" min="0" step="0.01" aria-label="Unit price" value={l.unit_price} placeholder="£ each"onChange={e=>setLine(i,'unit_price',e.target.value)}/><input type="number" min="0" step="0.01" aria-label="VAT rate" value={l.vat_rate} placeholder="VAT %"onChange={e=>setLine(i,'vat_rate',e.target.value)}/><button className="icon-btn"aria-label="Remove line"onClick={()=>removeLine(i)}><Trash2 size={17}/></button></div>)}</div><label>Notes<textarea value={notes}onChange={e=>setNotes(e.target.value)}placeholder="Optional quote notes"/></label><div className="detail-grid"><div><span>Subtotal</span><strong>£{subtotal.toFixed(2)}</strong></div><div><span>VAT</span><strong>£{lineVat.toFixed(2)}</strong></div><div><span>Total</span><strong>£{total.toFixed(2)}</strong></div></div><button className="primary wide"disabled={saving}onClick={save}><Save size={18}/>{saving?'Saving…':'Save quote'}</button></div><section className="section"><div className="section-head"><h2>Saved quotes</h2><span className="hint">{quotes.length} saved</span></div>{quotes.length?quotes.slice(0,10).map(q=><div className="job-card"key={q.id}><div className="job-top"><span className="job-id">QUOTE {q.quote_number}</span><span className="status">{String(q.status).replaceAll('_',' ')}</span></div><div className="card-title">{q.customers?.name||'No customer'}</div><div className="meta"><span>Subtotal £{Number(q.subtotal||0).toFixed(2)}</span><span>VAT £{Number(q.vat||0).toFixed(2)}</span><span>Total £{Number(q.total||0).toFixed(2)}</span></div></div>):<div className="empty-state"><FileText size={30}/><strong>No saved quotes yet</strong><span>Create the first quote above.</span></div>}</section></>;
}